const SPOTS_2 = [
 {
    id: "caen_chateau",
    name: "Caen - Château Ducal",
    country: "France",
    continent: "Europe",
    flag: "🇫🇷",
    region_admin: "Normandie",
    department: "Calvados (14)",
    subdiv: "Caen",
    altitude: 29,
    is_island: false,
    island_name: "",
    transport: "a_pied",
    era_group: "medieval",
    era_label: "Forteresse Ducale & Résidence des Ducs de Normandie",
    century: "XIe siècle (1060)",
    category: "chateau",
    counts: {},
    lat: 49.187161,
    lng: -0.363092,
    image: "https://lh3.googleusercontent.com/pw/AP1GczPwMeOlN2hghhfFMthOB7kcVP7h-ovzWNgjBNXqWJA_T_C3c02-uja0nC7S7upJA-KPBoOwprIpobgiHMAhTOHDJmJ14nU0tBYZQZyrrD6V-QBwP2nWKwvxEsdhHb3Ze-s8VERAdFrT5g3qbaYOPhjAVw=w1379-h919-s-no-gm?authuser=0",
    description: "Fondée vers 1060 par Guillaume le Conquérant sur un promontoire calcaire dominant la vallée de l'Orne, cette vaste forteresse s'étend sur plus de cinq hectares, ce qui en fait l'une des plus grandes enceintes médiévales fortifiées d'Europe. Conçu à l'origine pour affirmer l'autorité ducale sur la plaine de Caen, le site est profondément remanié au fil des siècles, notamment par Henri Ier Beauclerc qui y fait bâtir un imposant donjon roman carré et la célèbre salle de l'Échiquier de Normandie, remarquable témoin de l'architecture civile anglo-normande du XIIe siècle. Sous la domination des rois de France, Philippe Auguste ordonne le creusement de fossés monumentaux et la construction de la chemise du donjon, avant que la guerre de Cent Ans n'entraîne la modernisation des défenses, matérialisée par la porte Saint-Pierre flanquée de puissantes tours à mâchicoulis et la barbacane de la porte des Champs. Transformé en caserne militaire après la Révolution, le château subit de lourds bombardements lors des combats acharnés de l'été 1944. Les destructions des casernements modernes ont toutefois permis de dégager la cour intérieure et de mettre au jour les structures médiévales originelles. Aujourd'hui restauré, le site forme le cœur patrimonial de la ville, abritant dans son écrin de remparts en pierre de Caen le musée des Beaux-Arts et le musée de Normandie.",
    visiter: "Gravir les escaliers menant au chemin de ronde des remparts pour profiter d'un panorama circulaire exceptionnel sur les toits de la ville et les flèches des églises médiévales. Franchir la porte fortifiée des Champs avec son châtelet défensif et sa barbacane avant de traverser la vaste cour haute arborée. S'arrêter devant l'austère salle romane de l'Échiquier de Normandie afin d'en observer les baies géminées, puis explorer les vestiges archéologiques consolidés du donjon de Philippe Auguste et les jardins botaniques aménagés au pied des courtines.",
    link: "https://photos.google.com/share/AF1QipP_r-RkUhVBFruOXfc_tByvx5Vje8hgDNED4vVuvCKE6Q2NOmmiqdkWxaQaeFwASQ?key=TklDZmxVZGF4ZTJiaDFUbExPRlJXTkRlLXZzemdB"
  },
  {
    id: "caen_musee_des_beaux_arts",
    name: "Caen - Musée des Beaux-Arts",
    country: "France",
    continent: "Europe",
    flag: "🇫🇷",
    region_admin: "Normandie",
    department: "Calvados (14)",
    subdiv: "Caen",
    altitude: 29,
    is_island: false,
    island_name: "",
    transport: "a_pied",
    era_group: "contemporain",
    era_label: "Architecture Muséale Moderne & Peinture Européenne",
    century: "XXe siècle (1971)",
    category: "musee",
    counts: {},
    lat: 49.186291,
    lng: -0.361673,
    image: "https://lh3.googleusercontent.com/pw/AP1GczOEHaZslcQSlmW6Ethv6dvRe0u_EWEzgi_BHScYiWfpd9t02CIQHjrpJbqkjtUKDaG4j-NljCxCx0s0kyQK_Mk6q0QuGqlGyiZ0jiq0DIDB9vw5ldUDUVEUUvK0YyYwMQxv_tAakrVWvDAooeBbhi-KBQ=w613-h919-s-no-gm?authuser=0",
    description: "Implanté au cœur de l'enceinte fortifiée du château ducal, le musée des Beaux-Arts de Caen prend place dans un édifice novateur conçu par l'architecte Jean Atienza et inauguré en 1971. Ce bâtiment moderne et sobre, semi-enterré et habillé de calcaire clair afin de s'intégrer harmonieusement à l'austérité minérale des murailles médiévales environnantes, remplace l'ancien musée détruit lors des bombardements alliés de 1944 au sein du séminaire des Eudistes. L'institution conserve l'un des fonds de peinture les plus riches de France en région, dont le noyau historique provient des saisies révolutionnaires enrichies en 1801 par l'envoi consulaire du décret Chaptal. Les galeries permanentes offrent un parcours chronologique dense à travers l'art européen du XIVe au XXIe siècle, illustré par des chefs-d'œuvre majeurs de la Renaissance italienne et flamande avec Le Pérugin, Cosme Tura, Véronèse ou Brueghel le Jeune. Les collections brillent tout particulièrement par leur ensemble baroque du XVIIe siècle, comptant des toiles maîtresses de Nicolas Poussin, Philippe de Champaigne, Rubens et Le Guerchin, ainsi que par un remarquable panorama de la peinture française des XIXe et XXe siècles. L'expérience muséale s'étend à l'extérieur dans la cour du château avec un vaste parc de sculptures contemporaines exposant des œuvres monumentales signées Rodin, Bourdelle ou Huang Yong Ping.",
    visiter: "Entrer par la vaste façade vitrée ouvrant sur la cour haute pour apprécier la luminosité zénithale des salles d'exposition et la circulation fluide du bâtiment. Rechercher en priorité dans les salles de peinture ancienne le célèbre retable du Mariage de la Vierge du Pérugin et les grandes toiles classiques de Nicolas Poussin. Terminer la découverte en plein air en parcourant le jardin des sculptures contemporaines disséminé sur les pelouses bordant les remparts du château.",
    link: "https://photos.google.com/share/AF1QipP_r-RkUhVBFruOXfc_tByvx5Vje8hgDNED4vVuvCKE6Q2NOmmiqdkWxaQaeFwASQ?key=TklDZmxVZGF4ZTJiaDFUbExPRlJXTkRlLXZzemdB"
  },
  {
    id: "caen_eglise_saint_georges",
    name: "Caen - Église Saint-Georges du Château",
    country: "France",
    continent: "Europe",
    flag: "🇫🇷",
    region_admin: "Normandie",
    department: "Calvados (14)",
    subdiv: "Caen",
    altitude: 29,
    is_island: false,
    island_name: "",
    transport: "a_pied",
    era_group: "medieval",
    era_label: "Chapelle Castrale & Architecture Gothique Normande",
    century: "XIIe siècle",
    category: "religieux",
    counts: {},
    lat: 49.185939,
    lng: -0.362675,
    image: "https://lh3.googleusercontent.com/pw/AP1GczOHHE63OVvmuEXdd4QNW41abqfQSZPL51EWenOdTyUqLUvG8IDgiubnrfRIGnGsM5mTE5Gg2GVJkzdvaRRGlrzHrBUpi6oPs81zyWT-0YogxxEXQtm44nn3DWW2V9-XLT3ajM61OgmvFQ6LO2hHJBx0rA=w1379-h919-s-no-gm?authuser=0",
    description: "Érigée à l'intérieur même de l'enceinte castrale de Guillaume le Conquérant, l'église Saint-Georges assurait sous le duché de Normandie les fonctions de chapelle castrale et de paroisse réservée à la garnison ainsi qu'aux civils résidant dans la haute cour. Mentionnée dès les dernières décennies du XIe siècle, la structure primitive romane a fait l'objet de reconstructions successives et profondes, principalement au cours des XIVe et XVe siècles durant la guerre de Cent Ans. L'édifice actuel, appareillé en pierre calcaire de Caen, illustre la sobriété du gothique normand avec sa nef unique charpentée et son chœur à chevet plat percé de baies lancéolées aux réseaux polylobés délicats. Utilisée comme magasin à poudre puis comme salle de stockage militaire lorsque la forteresse ducale fut reconvertie en caserne au cours des XVIIIe et XIXe siècles, l'église subit d'importantes dégradations intérieures avant d'être sévèrement endommagée par les bombardements de 1944. Restaurée avec soin dans l'après-guerre et désacralisée, elle a été pourvue d'une charpente apparente en berceau évoquant une coque de navire renversée. L'édifice sert désormais d'écrin patrimonial pour l'accueil du musée de Normandie, présentant des expositions temporaires et de grandes maquettes retraçant les métamorphoses topographiques de la forteresse à travers les époques.",
    visiter: "Contempler depuis la pelouse de la cour ducale le profil modeste du chevet plat et les contreforts élancés soutenant les parois calcaires de l'édifice. Pénétrer dans le vaisseau unique pour lever les yeux vers la remarquable charpente en bois formant une voûte lambrissée continue. Détailler les vestiges d'inscriptions et de pierres tombales anciennes enchâssées dans le dallage, ainsi que les panneaux explicatifs et maquettes didactiques retraçant l'évolution médiévale de l'enceinte castrale.",
    link: "https://photos.google.com/share/AF1QipP_r-RkUhVBFruOXfc_tByvx5Vje8hgDNED4vVuvCKE6Q2NOmmiqdkWxaQaeFwASQ?key=TklDZmxVZGF4ZTJiaDFUbExPRlJXTkRlLXZzemdB"
  },
  {
    id: "caen_le_vieux_caen",
    name: "Caen - Le Vieux Caen (Quartier du Vaugueux)",
    country: "France",
    continent: "Europe",
    flag: "🇫🇷",
    region_admin: "Normandie",
    department: "Calvados (14)",
    subdiv: "Caen",
    altitude: 13,
    is_island: false,
    island_name: "",
    transport: "a_pied",
    era_group: "renaissance",
    era_label: "Quartier Historique Préservé & Maisons à Pans de Bois",
    century: "XVIe siècle",
    category: "star",
    counts: {},
    lat: 49.185445,
    lng: -0.359451,
    image: "https://lh3.googleusercontent.com/pw/AP1GczNMtcSFT5nTP6cmD-3SjxmKevACIU3vzgmDO-BiFY0lixyb31rq4Mq2BEkQ5hvFrvkgG_KkIMOC8SiyNy8ePFndOI2IRrxswTO4kwblOzI4lDK1jukMaMHFoKlTbIWUWY0ZwkhUYqtzvqlJWqnqJr7CRg=w1379-h919-s-no-gm?authuser=0",
    description: "Niché au pied des courtines orientales du château ducal, dans le vallon reliant la forteresse à l'abbaye aux Dames, le quartier du Vaugueux constitue l'un des rares îlots médiévaux et Renaissance ayant survécu aux bombardements dévastateurs de la bataille de Normandie en 1944. Ancien faubourg populaire et commerçant établi hors des remparts primitifs dès le Moyen Âge, ce dédale de venelles pavées et étroites est bordé de remarquables demeures construites entre les XVe et XVIIe siècles. Les façades témoignent d'une juxtaposition pittoresque entre la pierre calcaire de Caen, employée pour les rez-de-chaussée et les encadrements de fenêtres à meneaux, et les élévations traditionnelles à pans de bois hourdés de torchis ou de briques. Parmi ses étroites ruelles, la rue du Vaugueux et la rue Porte-au-Berger conservent des façades à encorbellement et de petits passages pavés caractéristiques du tissu urbain normand pré-moderne. Le quartier est également célèbre pour avoir été le lieu d'enfance d'Édith Piaf, qui venait régulièrement y séjourner chez sa grand-mère tenant une maison close rue des Chanoines. Entièrement réhabilité et piétonnisé à partir des années 1970, le secteur forme aujourd'hui le principal cœur gastronomique et animé du centre historique caennais.",
    visiter: "Arpenter la rue pavée du Vaugueux le nez en l'air pour repérer les sablières sculptées, les poteaux corniers ouvragés et les étages en encorbellement des maisons à pans de bois du XVIe siècle. S'engouffrer dans les passages piétons et cours intérieures pavées pour observer les escaliers à vis hors-œuvre taillés dans la pierre de Caen. Profiter de l'ambiance chaleureuse en soirée lorsque les terrasses s'animent face aux façades illuminées au pied du château.",
    link: "https://photos.google.com/share/AF1QipP_r-RkUhVBFruOXfc_tByvx5Vje8hgDNED4vVuvCKE6Q2NOmmiqdkWxaQaeFwASQ?key=TklDZmxVZGF4ZTJiaDFUbExPRlJXTkRlLXZzemdB"
  },
  {
    id: "caen_eglise_saint_pierre",
    name: "Caen - Église Saint-Pierre",
    country: "France",
    continent: "Europe",
    flag: "🇫🇷",
    region_admin: "Normandie",
    department: "Calvados (14)",
    subdiv: "Caen",
    altitude: 6,
    is_island: false,
    island_name: "",
    transport: "a_pied",
    era_group: "renaissance",
    era_label: "Gothique Flamboyant & Chevet Renaissance d'Hector Sohier",
    century: "XIVe siècle",
    category: "religieux",
    counts: {},
    lat: 49.184094,
    lng: -0.360846,
    image: "https://lh3.googleusercontent.com/pw/AP1GczNIsjJrY1c5wMWo5uAJ6qf_8w4dzYSn-LWx_gDrN8goKWX75jW3c-1kZ5uY1zYhYtwo1uIg1oHsqnqavrM2xAw8FpjpCQ1EhDRUYRuCBPSY9KB3BA0fCrbQDTinUHaf-TceVev9AoMWxxu6a7Guxvb6sQ=w1379-h919-s-no-gm?authuser=0",
    description: "Édifiée face aux douves méridionales du château ducal, l'église Saint-Pierre est le principal sanctuaire paroissial du centre historique de Caen et un chef-d'œuvre de la transition stylistique entre le Moyen Âge et la Renaissance. Construit par étapes entre le XIIIe et le XVIe siècle en pierre de Caen, l'édifice est dominé par une prestigieuse tour-clocher du tout début du XIVe siècle, couronnée d'une flèche pyramidale ajourée culminant à plus de soixante-quinze mètres de hauteur, prototype admiré dans toute la Normandie. La nef et les bas-côtés illustrent l'épanouissement du gothique flamboyant avec leurs voûtes à liernes et tiercerons et leurs grandes verrières aux remplages tourmentés. La renommée architecturale de Saint-Pierre repose toutefois sur son chevet d'exception, commandé au maître-maçon normand Hector Sohier entre 1518 et 1545. Ce dernier y déploie un vocabulaire maniériste d'une virtuosité éclatante, ornant les chapelles rayonnantes de voûtes suspendues à pendentifs sculptés vertigineux, de balustrades en candélabres, de pilastres antiquisants et d'angelots d'inspiration italienne. Frappée de plein fouet par un obus de marine britannique dans la nuit du 8 au 9 juin 1944 qui fit s'effondrer sa célèbre flèche sur la nef, l'église a fait l'objet d'une campagne de reconstruction exemplaire achevée en 1957.",
    visiter: "Contempler depuis la place Saint-Pierre l'élancement remarquable du clocher gothique et sa flèche octogonale ajourée réédifiée à l'identique après-guerre. Contourner impérativement l'édifice par la rue de Geôle pour admirer les chapelles rayonnantes du chevet conçues par Hector Sohier, foisonnantes de culots, de niches et de pinacles Renaissance. Franchir le portail sud pour lever les yeux vers les spectaculaires voûtes à clés pendantes du déambulatoire, véritables dentelles de pierre sculptées au XVIe siècle.",
    link: "https://photos.google.com/share/AF1QipP_r-RkUhVBFruOXfc_tByvx5Vje8hgDNED4vVuvCKE6Q2NOmmiqdkWxaQaeFwASQ?key=TklDZmxVZGF4ZTJiaDFUbExPRlJXTkRlLXZzemdB"
  },
  {
    id: "caen_eglise_vieux_saint_sauveur",
    name: "Caen - Église du Vieux Saint-Sauveur",
    country: "France",
    continent: "Europe",
    flag: "🇫🇷",
    region_admin: "Normandie",
    department: "Calvados (14)",
    subdiv: "Caen",
    altitude: 7,
    is_island: false,
    island_name: "",
    transport: "a_pied",
    era_group: "medieval",
    era_label: "Gothique Flamboyant & Église Déconsacrée",
    century: "XVe siècle",
    category: "religieux",
    counts: {},
    lat: 49.183398,
    lng: -0.367815,
    image: "https://lh3.googleusercontent.com/pw/AP1GczMWB4hi6zQnPKSnstqereSZxpOXSy31gJuBs82-Ti2uezyHfXiNr_mxzRFzeLVOEBIkvzuZxzsK3sdxkeRZV6_hnF7ch956M7dX3Y42VtVTJ4SL0cmfzfVsPKaRoEWnWTcQCy03uGkbQADvcpWrz-76EA=w1379-h919-s-no-gm?authuser=0",
    description: "Dressée sur la place Saint-Sauveur au cœur du quartier marchand médiéval de Caen, l'ancienne église paroissiale Saint-Sauveur, dite du « Vieux Saint-Sauveur », offre un précieux témoignage des transformations de l'architecture religieuse normande entre la fin du Moyen Âge et la Renaissance. Initialement fondée sous le règne de Guillaume le Conquérant, l'église conserve dans son clocher latéral des maçonneries du XIIe siècle, mais son allure générale résulte des reconstructions intégrales menées aux XIVe et XVe siècles dans le style gothique flamboyant. Son plan insolite présente une double nef asymétrique, dictée par les contraintes d'alignement parcellaire et l'adjonction progressive de chapelles de confréries. Le chœur à chevet polygonal, réédifié vers 1530-1546 dans l'orbite stylistique des ateliers d'Hector Sohier, mêle arcs brisés et décors sculptés influencés par la Première Renaissance française. Déconsacrée lors de la Révolution au profit de l'église des Cordeliers voisine (qui reprit alors le titre de Saint-Sauveur), la bâtisse échappe de justesse à la démolition pour servir de halle aux blés tout au long du XIXe siècle. Bien que durement éprouvée par les souffles d'explosions et les incendies lors des bombardements alliés de 1944, ses voûtes et ses élévations extérieures en pierre calcaire de Caen ont été minutieusement consolidées, devenant un espace d'expositions culturelles.",
    visiter: "Prendre du recul depuis la vaste place Saint-Sauveur pour apprécier l'asymétrie curieuse de la façade et la silhouette massive de la tour romane coiffée d'une toiture en bâtière. Examiner le chevet polygonal donnant sur la rue Pasteur afin de repérer les détails Renaissance sculptés sur les corniches et les remplages flamboyants des fenêtres hautes. Accéder à l'intérieur lors des manifestations artistiques pour observer le double vaisseau dégagé, les culots sculptés et les vestiges des voûtes en croisée d'ogives.",
    link: "https://photos.google.com/share/AF1QipP_r-RkUhVBFruOXfc_tByvx5Vje8hgDNED4vVuvCKE6Q2NOmmiqdkWxaQaeFwASQ?key=TklDZmxVZGF4ZTJiaDFUbExPRlJXTkRlLXZzemdB"
  },
 {
    id: "caen_vestiges_eglise_saint_gilles",
    name: "Caen - Vestiges de l'Ancienne Église Saint-Gilles",
    country: "France",
    continent: "Europe",
    flag: "🇫🇷",
    region_admin: "Normandie",
    department: "Calvados (14)",
    subdiv: "Caen",
    altitude: 24,
    is_island: false,
    island_name: "",
    transport: "a_pied",
    era_group: "medieval",
    era_label: "Ruines Médiévales & Vestiges des Bombardements",
    century: "XIIe siècle",
    category: "religieux",
    counts: {},
    lat: 49.186571,
    lng: -0.354644,
    image: "https://lh3.googleusercontent.com/pw/AP1GczOdTSSUgq8bTEUGUMleRlHw0QzbL6f_4ePRneIJ-qaHuVvOLQyJxwUBtmcH1gjgToHe4ZxJ3lrPjagPJYHUYwr5kf4Ddq3BHTrwbgpjDfG_0B51JcbVL2d2zDGK5Yy_ijTGkzxJrruoc2h7k2GNSt43sw=w1800-h1201-s-no-gm?authuser=0",
    description: "Dressées au sommet de la colline de la Trinité, à quelques pas de l'enclos monastique de l'abbaye aux Dames, les ruines de l'église Saint-Gilles constituent un témoignage saisissant des ravages de la Seconde Guerre mondiale au cœur de la capitale bas-normande. Fondée initialement au début du XIIe siècle, vers 1110, par la reine Mathilde de Flandre et complétée par son époux Guillaume le Conquérant pour servir d'église paroissiale aux habitants et dépendants du domaine abbatial, la paroisse fut dotée d'un premier édifice roman en pierre de Caen. Reconstruite et agrandie aux XIVe et XVe siècles avec l'adjonction de chapelles latérales et d'éléments de modénature gothique flamboyant, l'église présentait un plan allongé typique de l'architecture urbaine médiévale normande. Le monument traverse les siècles et la Révolution sans dommage majeur, devenant un sujet privilégié pour les peintres paysagistes et les lithographes romantiques du XIXe siècle. Lors de la bataille de Caen à l'été 1944, l'édifice est directement touché et anéanti par les intenses bombardements aériens et les tirs d'artillerie alliés préparant la libération de la ville. Plutôt que de reconstruire le sanctuaire disparu, la municipalité et les Monuments historiques ont fait le choix de stabiliser et de consolider à ciel ouvert les pans de murs, les amorces d'arcatures brisées et les bases des piliers calcinés, offrant un cénotaphe végétalisé en plein air qui dialogue avec le patrimoine mémorial caennais.",
    visiter: "Pénétrer dans le square paysager aménagé autour des vestiges pour détailler le tracé au sol de l'ancienne nef et du chœur délimités par les soubassements en pierre de Caen. Observer les amorces d'arcs brisés et les moulurations gothiques érodées qui subsistent sur les quelques pans de maçonnerie restés debout. Prendre le recul nécessaire depuis le haut de la place Reine-Mathilde pour saisir le contraste visuel saisissant entre la nudité minérale de ces ruines à ciel ouvert et les volumes intacts et imposants de l'abbatiale Sainte-Trinité toute proche.",
    link: "https://photos.google.com/share/AF1QipP_r-RkUhVBFruOXfc_tByvx5Vje8hgDNED4vVuvCKE6Q2NOmmiqdkWxaQaeFwASQ?key=TklDZmxVZGF4ZTJiaDFUbExPRlJXTkRlLXZzemdB"
  },
  {
    id: "caen_abbaye_aux_dames",
    name: "Caen - Abbaye aux Dames",
    country: "France",
    continent: "Europe",
    flag: "🇫🇷",
    region_admin: "Normandie",
    department: "Calvados (14)",
    subdiv: "Caen",
    altitude: 24,
    is_island: false,
    island_name: "",
    transport: "a_pied",
    era_group: "medieval",
    era_label: "Chefd'œuvre de l'Art Roman Normand & Tombeau de la Reine Mathilde",
    century: "XIe siècle (1060)",
    category: "religieux",
    counts: {},
    lat: 49.186476,
    lng: -0.353019,
    image: "https://lh3.googleusercontent.com/pw/AP1GczMXr0Z5eyh8zozv-xGP1-ej_UmH35fUy6tzJ1qFyrf0RGCRRikrAioNuc3FtMaIsUSHHbl03Xpn3F2mRnh7qMnwFQstxvmZRNuiLqta5KIdLWmxPobJs2Xp5tzxt_iacO9FDGfabn0Qr8677xck1QLLTw=w1800-h1201-s-no-gm?authuser=0",
    description: "Fondée vers 1060 par Mathilde de Flandre, épouse de Guillaume le Conquérant, l'abbaye aux Dames (consacrée sous le vocable de la Trinité) est l'un des plus illustres ensembles monastiques de Normandie. Conçue comme l'homologue féminin de l'abbaye aux Hommes, cette fondation bénédictine royale visait à sceller la réconciliation du couple ducal avec la papauté après leur mariage célébré malgré un degré de consanguinité prohibé par le droit canonique. L'église abbatiale, consacrée en 1066 à la veille du départ de la flotte d'invasion vers l'Angleterre, est un sommet de l'architecture romane normande. Construite en pierre calcaire de Caen aux teintes dorées, sa nef imposante présente une élévation à trois niveaux surmontée, dès le début du XIIe siècle, de voûtes d'arêtes sexpartites parmi les premières et les plus hardies de l'Occident chrétien. Le sanctuaire abrite au centre de son chœur la sépulture historique de la reine Mathilde, signalée par une magnifique dalle funéraire de marbre noir du Tournaisis gravée de caractères carolingiens. Au XVIIIe siècle, les bâtiments conventuels furent entièrement reconstruits dans un style classique monumental par l'architecte Guillaume de La Tremblaye, ordonnés autour d'un cloître majestueux et d'un grand escalier d'honneur. Miraculeusement épargnée par les bombardements de 1944 grâce à son statut de refuge hospitalier sous égide de la Croix-Rouge, l'abbaye abrite aujourd'hui le siège du Conseil régional de Normandie.",
    visiter: "Franchir le porche occidental pour contempler la pureté des lignes de la nef romane et la hardiesse technique de ses voûtes d'ogives sexpartites du début du XIIe siècle. S'avancer vers le chœur liturgique afin de se recueillir devant la dalle de marbre noir gravée recouvrant la sépulture de la reine Mathilde. Descendre impérativement dans la crypte romane souterraine, véritable forêt minérale soutenue par seize colonnes monolithes coiffées de chapiteaux historiés remarquablement conservés, avant de déambuler dans les jardins à la française et le parc Michel d'Ornano attenant.",
    link: "https://photos.google.com/share/AF1QipP_r-RkUhVBFruOXfc_tByvx5Vje8hgDNED4vVuvCKE6Q2NOmmiqdkWxaQaeFwASQ?key=TklDZmxVZGF4ZTJiaDFUbExPRlJXTkRlLXZzemdB"
  },
  {
    id: "caen_abbaye_aux_hommes",
    name: "Caen - Abbaye aux Hommes",
    country: "France",
    continent: "Europe",
    flag: "🇫🇷",
    region_admin: "Normandie",
    department: "Calvados (14)",
    subdiv: "Caen",
    altitude: 12,
    is_island: false,
    island_name: "",
    transport: "a_pied",
    era_group: "medieval",
    era_label: "Monument Majeur de l'Art Anglo-Normand & Tombeau de Guillaume le Conquérant",
    century: "XIe siècle (1063)",
    category: "religieux",
    counts: {},
    lat: 49.181852,
    lng: -0.37316,
    image: "https://lh3.googleusercontent.com/pw/AP1GczNq8cpJNL1VGeUl2J0GhsXep2gSyUlt-3AOaadXs_FBx6PsL-MY82KZ3EmBr8UB9jKZuPWFXYq3BlSmjYjFHG9mpMJ-vMAifpjJcOvChjir6NbeUFHRyXtMsa3xALq3HvZPg47D7FmDVn_YG0WW1lqKEQ=w1800-h1201-s-no-gm?authuser=0",
    description: "Fondée en 1063 par Guillaume le Conquérant, duc de Normandie et futur roi d'Angleterre, l'abbaye aux Hommes, dédiée à saint Étienne, forme avec l'abbaye aux Dames le pendant de la pénitence matrimoniale imposée par le pape Léon IX. Chef-d'œuvre fondateur de l'architecture anglo-normande, son abbatiale Saint-Étienne a profondément inspiré les grandes cathédrales d'outre-Manche telles que Durham, Winchester ou Ely. Bâtie en pierre calcaire de Caen, la façade harmonique occidentale offre un modèle d'équilibre et de puissance austère, structurée par de vigoureux contreforts verticaux et sommée de deux imposantes tours romanes couronnées au XIIIe siècle par d'admirables flèches octogonales gothiques culminant à plus de quatre-vingts mètres. L'intérieur de la nef s'élève sur trois niveaux d'une grande rigueur géométrique et accueille le prototype canonique de la voûte d'ogives sexpartite expérimentée vers 1120. Le sanctuaire abrite dans son chœur la dalle tombale de marbre blanc marquant l'emplacement de la sépulture de Guillaume le Conquérant, inhumé ici en 1087 lors d'obsèques mouvementées. Aux XVIIe et XVIIIe siècles, la congrégation de Saint-Maur métamorphosa les bâtiments conventuels attenants en un palais monastique d'esprit classique grandiose, articulé autour d'un vaste cloître toscan et d'un escalier d'honneur en fer forgé. Devenu lycée au XIXe siècle puis hôtel de ville de Caen en 1965, le site a servi d'immense camp de réfugiés sous la protection de la Croix-Rouge lors de l'été 1944, ce qui lui valut d'échapper miraculeusement aux bombardements.",
    visiter: "Admirer depuis l'esplanade Jean-Marie Louvel la façade harmonique et la verticalité des flèches gothiques s'élançant au-dessus des tours romanes. Pénétrer dans l'abbatiale Saint-Étienne pour apprécier la clarté et l'ampleur monumentale de la nef tripartite, puis s'avancer jusqu'au chœur pour observer la dalle funéraire de marbre blanc signalant le tombeau de Guillaume le Conquérant. Prolonger la visite dans les bâtiments conventuels de l'actuel hôtel de ville afin d'admirer les galeries voûtées du cloître classique, le monumental escalier des matines et les lambris de chêne de la salle des mariages.",
    link: "https://photos.google.com/share/AF1QipP_r-RkUhVBFruOXfc_tByvx5Vje8hgDNED4vVuvCKE6Q2NOmmiqdkWxaQaeFwASQ?key=TklDZmxVZGF4ZTJiaDFUbExPRlJXTkRlLXZzemdB"
  },
 {
    id: "ouistreham_musee_mur_atlantique",
    name: "Ouistreham - Musée du Mur de l'Atlantique",
    country: "France",
    continent: "Europe",
    flag: "🇫🇷",
    region_admin: "Normandie",
    department: "Calvados (14)",
    subdiv: "Ouistreham",
    altitude: 6,
    is_island: false,
    island_name: "",
    transport: "a_pied",
    era_group: "contemporain",
    era_label: "Poste de Direction de Tir & Fortification Militaire",
    century: "XXe siècle (1944)",
    category: "musee",
    counts: {},
    lat: 49.287416,
    lng: -0.252389,
    image: "https://lh3.googleusercontent.com/pw/AP1GczM5LVSYmdJQ_NSahpFAYMhVgtQqGFCvkOnzG69gltghHwezm7lumkeXp2wj_z_FU4bYRmR44ZGZvROA0vys8z_4ZqqLAG2mG1RIjMiP5nWMIwNZ5DWfss5YbZw1l1i5Ek0ZLX-83UigmT7wekmALWVYAA=w1800-h1201-s-no-gm?authuser=0",
    description: "Aménagé dans un authentique poste de direction de tir allemand (bunker de type Regelbau H636) achevé début 1944 par l'Organisation Todt, ce musée surnommé « Le Grand Bunker » culmine à dix-sept mètres de hauteur et domine l'embouchure de l'Orne et la baie de Seine. Ce monolithe de béton armé de cinq niveaux, doté de blindages étanches et de murs atteignant par endroits plus de deux mètres d'épaisseur, coordonnait le tir des batteries d'artillerie lourde côtières couvrant le secteur est de la plage de Sword Beach. Lors du Débarquement du 6 juin 1944, l'ouvrage verrouille le front fluvial et résiste pendant trois jours aux tirs de navires alliés et aux assauts terrestres. Il n'est neutralisé que le 9 juin par le lieutenant britannique Bob Orrell du Royal Engineers, qui parvient à dynamiter l'épaisse porte blindée après plusieurs heures d'un siège méthodique. Intégralement réhabilité et transformé en musée de site, le complexe restitue fidèlement l'ambiance confinée et technique de la garnison allemande à travers la reconstitution méticuleuse de ses chambrées, de son infirmerie, de ses salles des machines de filtration d'air, de son central téléphonique et de sa coupole télémétrique sommitale. L'extérieur abrite également la célèbre péniche de débarquement PA 30-4 ayant servi au tournage du film « Il faut sauver le soldat Ryan ».",
    visiter: "Gravir les paliers intérieurs pour explorer chaque niveau fonctionnel du bunker, depuis les installations de survie autonomes au sous-sol jusqu'au central radio parfaitement équipé. Atteindre le sommet pour regarder à travers les optiques du puissant télémètre à coïncidence sous coupole blindée, offrant une vue panoramique directe sur tout le littoral d'Ouistreham et la Manche. Examiner sur l'esplanade extérieure la barge de débarquement de type LCVP ainsi que les canons de DCA et pièces antichars d'époque.",
    link: "https://photos.google.com/share/AF1QipP_r-RkUhVBFruOXfc_tByvx5Vje8hgDNED4vVuvCKE6Q2NOmmiqdkWxaQaeFwASQ?key=TklDZmxVZGF4ZTJiaDFUbExPRlJXTkRlLXZzemdB"
  },
  {
    id: "ouistreham_grande_roue",
    name: "Ouistreham - Grande Roue de Riva-Bella",
    country: "France",
    continent: "Europe",
    flag: "🇫🇷",
    region_admin: "Normandie",
    department: "Calvados (14)",
    subdiv: "Ouistreham",
    altitude: 1,
    is_island: false,
    island_name: "",
    transport: "a_pied",
    era_group: "contemporain",
    era_label: "Panorama Balnéaire & Front de Mer",
    century: "XXIe siècle",
    category: "star",
    counts: {},
    lat: 49.290286,
    lng: -0.257242,
    image: "https://lh3.googleusercontent.com/pw/AP1GczOtlugBOJpMYjbHkce_Hr_E3tjfBnsRL95hCtCFYMZthHK9yu_CbujuUxTIs1ocH0sxnntq6uhAuiCYulhG--w6I_-AcBn1OgTZeCFjYB5ggVgEJDFbeUssodXnVySra_lld8VlMy29MySh9HjNF_fUYA=w1800-h1201-s-no-gm?authuser=0",
    description: "Dressée directement sur l'esplanade du front de mer de Riva-Bella, à la charnière entre le cordon dunaire et la promenade maritime, cette imposante attraction foraine panoramique culmine à près de quarante mètres de hauteur. Conçue avec une structure légère en treillis d'acier blanc et des nacelles ouvertes et vitrées, elle offre un contraste visuel marqué avec l'immense estran sableux découvert à marée basse et la ligne d'horizon rectiligne de la Côte de Nacre. Installée de façon pérenne ou saisonnière selon les périodes au cœur de la station balnéaire fondée au XIXe siècle, la structure permet d'embrasser d'un seul coup d'œil l'ensemble du dispositif topographique du littoral : les jetées du port d'Ouistreham marquant le débouché du canal maritime de Caen, la pointe du Siège et son cordon sableux préservé, ainsi que l'ensemble du secteur de débarquement anglo-français de Sword Beach. À la nuit tombée, son réseau d'éclairage dynamique à LED illumine la promenade piétonne, constituant un repère lumineux visible loin depuis la plage et les quais d'embarquement des ferries transmanche.",
    visiter: "S'approcher depuis la promenade piétonne du front de mer pour saisir en contre-plongée les lignes géométriques blanches de la charpente métallique se découpant sur le ciel marin. Monter à bord des nacelles au moment de la pleine mer ou au coucher du soleil afin de profiter d'un panorama circulaire exceptionnel sur la baie de l'Orne, les villas Belle Époque de Riva-Bella et l'estran de Sword Beach s'étirant vers l'ouest.",
    link: "https://photos.google.com/share/AF1QipP_r-RkUhVBFruOXfc_tByvx5Vje8hgDNED4vVuvCKE6Q2NOmmiqdkWxaQaeFwASQ?key=TklDZmxVZGF4ZTJiaDFUbExPRlJXTkRlLXZzemdB"
  },
  {
    id: "ouistreham_monument_la_flamme",
    name: "Ouistreham - Monument La Flamme",
    country: "France",
    continent: "Europe",
    flag: "🇫🇷",
    region_admin: "Normandie",
    department: "Calvados (14)",
    subdiv: "Ouistreham",
    altitude: 1,
    is_island: false,
    island_name: "",
    transport: "a_pied",
    era_group: "contemporain",
    era_label: "Mémorial aux Commandos Français de Sword Beach",
    century: "XXe siècle (1984)",
    category: "star",
    counts: {},
    lat: 49.290511,
    lng: -0.262337,
    image: "https://lh3.googleusercontent.com/pw/AP1GczOqQWsMDHr1XFUp-ojuG32vo_6VWvuNMRvKnzwMFFmXzhMHLVUmfq2rtWJW__pwJQR1imLSg-7oNjekhCIIow-cslkxiaAFRh0NFMtdJiiVFOLgncyIdQEV5ATPsMOn5qH1GOHmNZSEkiJ5Jy50apuvEQ=w1800-h1199-s-no-gm?authuser=0",
    description: "Érigé au sommet de la dune littorale bordant la plage de Riva-Bella, face à l'immensité de la Manche, le monument commémoratif « La Flamme » a été inauguré le 6 juin 1984 par le président de la République François Mitterrand à l'occasion du 40e anniversaire du Débarquement de Normandie. Œuvre monumentale en métal et béton signée de l'artiste Yvonne Guégan, la sculpture stylise sept langues d'acier inoxydable élancées vers le ciel pour symboliser l'esprit de résistance et l'élan héroïque des soldats de la France libre. L'ouvrage rend un hommage solennel aux cent soixante-dix-sept fusiliers marins du 1er bataillon de fusiliers marins commandos, placé sous le commandement direct du commandant Philippe Kieffer. Intégrés au commando interallié britannique n° 4 au sein de la 1st Special Service Brigade de Lord Lovat, ces hommes furent les seuls Français en uniforme à fouler la terre de Normandie le Jour J. Débarqués à 7 h 31 sous un feu nourri d'armes automatiques et de mortiers, ils eurent pour mission périlleuse d'enlever les redoutables fortifications côtières du point d'appui allemand Wn 10 (le site fortifié du Casino) avant de repiquer vers l'est pour opérer la jonction avec les parachutistes britanniques à Bénouville.",
    visiter: "Gravir les emmarchements de pierre qui mènent au socle surélevé pour contempler la dynamique verticale des lames de métal poli se reflétant dans la lumière côtière. Faire le tour de la base du monument afin de lire les plaques de bronze énumérant les noms des 177 commandos français du bataillon Kieffer, ainsi que les stèles rendant hommage aux disparus des combats du 6 juin. Tourner le regard vers le nord pour appréhender directement l'axe d'assaut des barges de débarquement arrivant sur l'estran découvert à marée basse.",
    link: "https://photos.google.com/share/AF1QipP_r-RkUhVBFruOXfc_tByvx5Vje8hgDNED4vVuvCKE6Q2NOmmiqdkWxaQaeFwASQ?key=TklDZmxVZGF4ZTJiaDFUbExPRlJXTkRlLXZzemdB"
  },
 {
    id: "ouistreham_eglise_saint_samson",
    name: "Ouistreham - Église Saint-Samson",
    country: "France",
    continent: "Europe",
    flag: "🇫🇷",
    region_admin: "Normandie",
    department: "Calvados (14)",
    subdiv: "Ouistreham",
    altitude: 10,
    is_island: false,
    island_name: "",
    transport: "a_pied",
    era_group: "medieval",
    era_label: "Architecture Romane Normande & Église Fortifiée",
    century: "XIIe siècle",
    category: "religieux",
    counts: {},
    lat: 49.276189,
    lng: -0.258053,
    image: "https://lh3.googleusercontent.com/pw/AP1GczNoUPf-BIDUT5rWYfb3z-EApkN9bid5MXnYlQbpvfjOOOOlzvWT8ezmgut-Cg5_X8I7lNGCGRDvGZNAvhHd6MapTOGjDa8QPOY3BrR06sE8qRg7H1kIeFe6MvgB9Esi28ej0LYrGvlCmAVitIsO1WW9hw=w1800-h1201-s-no-gm?authuser=0",
    description: "Édifiée à partir de la seconde moitié du XIIe siècle sur les hauteurs du bourg originel, l'église Saint-Samson constitue un jalon remarquable de l'art roman normand, construite en pierre calcaire de Caen. Dédiée à saint Samson de Dol, l'un des sept saints fondateurs de Bretagne ayant débarqué sur le littoral normand au VIe siècle, elle dépendait sous l'Ancien Régime de la prestigieuse abbaye aux Dames de Caen. L'édifice se distingue par son allure massive et austère, issue de son rôle défensif face aux incursions maritimes venues de la Manche : ses maçonneries épaisses, percées d'ouvertures étroites en meurtrières, servaient de refuge à la population locale, notamment durant les ravages de la guerre de Cent Ans. La façade occidentale est une pièce maîtresse de la sculpture romane régionale, structurée par trois registres d'arcatures aveugles en plein cintre et rythmée par un portail richement sculpté d'archivoltes à bâtons rompus, de frettes crénelées et de modillons figuratifs animaliers. À l'intérieur, la vaste nef romane à trois niveaux d'élévation mène à un chœur et une abside remaniés au XIIIe siècle dans un style gothique primitif élancé, marqué par des voûtes sur croisées d'ogives et des baies lancéolées apportant une vive clarté au sanctuaire. Classé monument historique dès 1840 sur la toute première liste établie par Prosper Mérimée, le monument a également été le témoin direct des combats acharnés menés le 6 juin 1944 par les commandos français du bataillon Kieffer lors de la libération du bourg.",
    visiter: "Prendre du recul sur le parvis pour détailler l'ornementation géométrique du portail ouest, en particulier les chevrons sculptés, les motifs d'entrelacs et la série de modillons anthropomorphes sous la corniche. Faire le tour extérieur par le chevet afin d'observer la transition architecturale entre les puissants contreforts romans de la nef et les baies gothiques plus élancées du chœur. Franchir le portail pour admirer l'élévation intérieure de la nef rythmée par ses grandes arcades retombant sur de lourdes piles circulaires, puis lever les yeux vers la croisée du transept pour examiner la lanterne octogonale coiffant la tour centrale.",
    link: "https://photos.google.com/share/AF1QipP_r-RkUhVBFruOXfc_tByvx5Vje8hgDNED4vVuvCKE6Q2NOmmiqdkWxaQaeFwASQ?key=TklDZmxVZGF4ZTJiaDFUbExPRlJXTkRlLXZzemdB"
  },
 {
    id: "benouville_pegasus_bridge",
    name: "Bénouville - Pegasus Bridge",
    country: "France",
    continent: "Europe",
    flag: "🇫🇷",
    region_admin: "Normandie",
    department: "Calvados (14)",
    subdiv: "Bénouville",
    altitude: 6,
    is_island: false,
    island_name: "",
    transport: "a_pied",
    era_group: "contemporain",
    era_label: "Ouvrage d'Art Métallique & Mémoire du Débarquement",
    century: "XXe siècle (1935)",
    category: "pont",
    counts: {},
    lat: 49.242332,
    lng: -0.273935,
    image: "https://lh3.googleusercontent.com/pw/AP1GczNYr1V1dfwoTR4Kea3DMnCa3VuVOSf8_W6IkWwgGMXx3ol0iPrMoNCu52nqaorKPR4q8BqykZi2tmIPGaXynQ3t8ItNyNIgUJRXubr30MeqKkRQ2Az-kvGPgMZ-3vvOr-DlgvXnYP4OErfyynWvZgWAaA=w1800-h1199-s-no-gm?authuser=0",
    description: "Édifié en 1935 pour franchir le canal de Caen à la mer et relier Bénouville à Ranville, cet ouvrage d'art est un pont basculant métallique à bascule roulante de type Scherzer, reconnaissable à son imposant contrepoids aérien et à ses poutres en treillis riveté. Le site entre dans l'histoire universelle dans la nuit du 5 au 6 juin 1944, lors de l'opération aéroportée Deadstick menée sous le commandement du major John Howard. Déposés à bord de trois planeurs Airspeed Horsa à moins de cinquante mètres des défenses allemandes, les hommes de la 6e division aéroportée britannique de la British Army s'emparent de l'ouvrage en une dizaine de minutes seulement. Cet exploit tactique éclair visait à sécuriser le flanc est de la zone de débarquement d'Ouistreham (Sword Beach) et à empêcher tout contre-assaut de blindés ennemis sur les plages normandes. Rebaptisé officiellement Pegasus Bridge en l'honneur de l'insigne ailé des troupes aéroportées britanniques, le pont d'origine a été déposé et préservé en 1994 afin de permettre le recalibrage du canal maritime. Remplacé in situ par un modèle élargi reprenant scrupuleusement la cinématique et l'architecture industrielle d'origine, le tablier historique repose aujourd'hui dans l'enceinte du musée mémorial voisin.",
    visiter: "Rejoindre à pied le tablier pour examiner le système de bascule Scherzer, ses rails crantés et les contrepoids géants dominant la voie d'eau. Longer les rives du canal jusqu'à l'emplacement des points d'atterrissage des trois planeurs Horsa, matérialisés par des stèles commémoratives sur la rive orientale. Traverser ensuite vers le parc du Mémorial Pegasus afin d'approcher le pont original de 1935 et d'observer de près les traces d'impacts d'obus et de mitraille conservées sur son armature rivetée.",
    link: "https://photos.google.com/share/AF1QipP_r-RkUhVBFruOXfc_tByvx5Vje8hgDNED4vVuvCKE6Q2NOmmiqdkWxaQaeFwASQ?key=TklDZmxVZGF4ZTJiaDFUbExPRlJXTkRlLXZzemdB"
  },
  {
    id: "benouville_cafe_gondree",
    name: "Bénouville - Café Gondrée",
    country: "France",
    continent: "Europe",
    flag: "🇫🇷",
    region_admin: "Normandie",
    department: "Calvados (14)",
    subdiv: "Bénouville",
    altitude: 6,
    is_island: false,
    island_name: "",
    transport: "a_pied",
    era_group: "contemporain",
    era_label: "Bâtiment Historique de la Libération",
    century: "XIXe siècle",
    category: "habitation",
    counts: {},
    lat: 49.24241,
    lng: -0.275021,
    image: "https://lh3.googleusercontent.com/pw/AP1GczOgpuwhqpwlTw3rt4y9OMJkMaDOC2RpX5Iaor0vl3VY8oWl-ngpP9ooF21ka2E_nCpSiDyXrGSC_c4wmUFIg8aVAi7yqFkdiB35Os-8JfpzZHJpxhPlAvTet1Kz2UYKffc4jM9fjHIJa8qdW2foURB3Cw=w1800-h1201-s-no-gm?authuser=0",
    description: "Située sur la rive ouest du canal de Caen à la mer, à quelques dizaines de mètres de la tête de pont de Bénouville, cette bâtisse villageoise construite à la fin du XIXe siècle présente une maçonnerie modeste en briques et enduit sous une toiture d'ardoises. Elle est entrée dans l'histoire de la Seconde Guerre mondiale comme la première maison de France continentale libérée par les forces alliées, quelques minutes après minuit le 6 juin 1944. Tenu à l'époque par Georges et Thérèse Gondrée, qui transmettaient clandestinement des renseignements précieux à la Résistance sur les défenses allemandes locales, l'établissement est immédiatement investi par les hommes du major John Howard dès la prise de Pegasus Bridge. Transformé sur-le-champ en poste de secours médical de fortune, le rez-de-chaussée accueille et soigne les premiers blessés aéroportés de l'opération Overlord, dont le lieutenant Den Brotheridge mortellement touché lors de l'assaut. Toujours entretenu dans un esprit mémoriel vivant et resté propriété de la même famille, le bâtiment demeure un sanctuaire emblématique dédié aux parachutistes britanniques, arborant façades et intérieurs entièrement tapissés d'insignes régimentaires, d'objets militaires et de témoignages de vétérans.",
    visiter: "Observer depuis la berge et la rue les façades d'époque ornées d'enseignes régimentaires britanniques, de plaques commémoratives et de drapeaux alliés. Prendre le recul nécessaire face au canal pour mesurer l'extrême proximité géographique entre le seuil de la bâtisse et l'axe stratégique de Pegasus Bridge. Pénétrer à l'intérieur pour découvrir les murs tapissés de fanions, de photographies d'époque dédicacées par les vétérans et de souvenirs conservés intacts depuis juin 1944.",
    link: "https://photos.google.com/share/AF1QipP_r-RkUhVBFruOXfc_tByvx5Vje8hgDNED4vVuvCKE6Q2NOmmiqdkWxaQaeFwASQ?key=TklDZmxVZGF4ZTJiaDFUbExPRlJXTkRlLXZzemdB"
  },
];
