const SPOTS_2 = [
 {
    id: "cricqueville_en_bessin_pointe_du_hoc",
    name: "Cricqueville-en-Bessin - Pointe du Hoc",
    country: "France",
    continent: "Europe",
    flag: "🇫🇷",
    region_admin: "Normandie",
    department: "Calvados (14)",
    subdiv: "Cricqueville-en-Bessin",
    altitude: 18,
    is_island: false,
    island_name: "",
    transport: "a_pied",
    era_group: "nature,
    era_label: "Champ de Bataille & Exploit des Rangers",
    century: "XXe siècle (1944)",
    category: "star",
    counts: {},
    lat: 49.397908,
    lng: -0.989507,
    image: "https://lh3.googleusercontent.com/pw/AP1GczMGa12RhEv2kwjnLPDftw3TgYQpdr-HeqeTJ_SwSVXAtgaPKj2I8XwZy033Ye8LbxY19iCvoiezszwkoiRS-sqXQd1c9NRvC_wm_lhnaTHp11oDDHtehhkAOHuvd57l_4q79Vehshd4yJxcak8cssT1tg=w1379-h919-s-no-gm?authuser=0",
    description: "Avancée rocheuse dominant la Manche du haut de falaises de calcaire hautes d'une trentaine de mètres, la pointe du Hoc constituait une position stratégique majeure du mur de l'Atlantique, verrouillant l'espace maritime entre les plages de débarquement d'Utah Beach à l'ouest et d'Omaha Beach à l'est. L'Organisation Todt y avait aménagé une redoutable batterie côtière composée de six encuvements et casemates en béton armé armés de pièces de cent cinquante-cinq millimètres susceptibles de pilonner les flottes de débarquement alliées. Au matin du 6 juin 1944, deux cent vingt-cinq soldats d'élite du 2nd US Ranger Battalion, commandés par le lieutenant-colonel James Earl Rudder, prennent d'assaut cette position réputée imprenable. Escaladant la paroi verticale sous les tirs ennemis à l'aide de grappins, d'échelles de corde et de cordages propulsés par fusées, les Rangers parviennent au sommet au prix de lourdes pertes, découvrant que les canons avaient été déplacés en retrait dans les terres où ils finissent par les neutraliser. Le site a été préservé dans son état d'après-bataille, offrant un paysage lunaire bouleversé par des centaines de cratères d'obus d'artillerie navale et de bombes aériennes, jalonné de casemates disloquées et de bunkers éventrés.",
    visiter: "Suivre le cheminement balisé serpentant entre les profonds entonnoirs d'explosion tapissés d'herbe qui témoignent de la violence inouïe des bombardements préparatoires. Pénétrer dans les bunkers et abris souterrains en béton armé encore noircis par les déflagrations, puis s'avancer prudemment jusqu'au poste d'observation et de direction de tir coiffé du monument commémoratif des Rangers pour admirer le vide vertical des falaises plongeant dans la mer.",
    link: "https://photos.google.com/share/AF1QipP_r-RkUhVBFruOXfc_tByvx5Vje8hgDNED4vVuvCKE6Q2NOmmiqdkWxaQaeFwASQ?key=TklDZmxVZGF4ZTJiaDFUbExPRlJXTkRlLXZzemdB"
  },
  {
    id: "vierville_sur_mer_omaha_beach_wn72",
    name: "Vierville-sur-Mer - Omaha Beach (Wn 72)",
    country: "France",
    continent: "Europe",
    flag: "🇫🇷",
    region_admin: "Normandie",
    department: "Calvados (14)",
    subdiv: "Vierville-sur-Mer",
    altitude: 2,
    is_island: false,
    island_name: "",
    transport: "a_pied",
    era_group: "contemporain",
    era_label: "Point d'Appui Côtier & Percée du Secteur Charlie",
    century: "XXe siècle (1944)",
    category: "star",
    counts: {},
    lat: 49.380117,
    lng: -0.903629,
    image: "https://lh3.googleusercontent.com/pw/AP1GczNiE3_2OvbBKIstO4-76lhWTsVVovTTLl0qoX1BFlwaRD0DbJeHpcVe4h04JKZyfohJgLxSTa1NZh06zg_PsCenSZEZ9xlN3E4fNJaRUfEchtPrv944QrNrpDNpXYH5e4RP5LPi6WAC70-8rySPw3J1og=w1379-h919-s-no-gm?authuser=0",
    description: "Implanté à la sortie ouest de la plage d'Omaha Beach, le Widerstandsnest 72 (nid de résistance 72) était un ensemble fortifié allemand conçu pour interdire tout accès au vallon de Vierville-sur-Mer par la coupure naturelle dite sortie D-1. Intégré au dispositif côtier de la 352e division d'infanterie allemande, ce complexe défensif redoutable comprenait une casemate de type Regelbau H667 abritant un canon antichar de cinquante millimètres orienté en enfilade le long de la grève, des tobrouks pour mitrailleuses, des réseaux de barbelés denses et des fossés antichars creusés dans le cordon de galets. Le 6 juin 1944, les troupes de la 29e division d'infanterie américaine et des compagnies de Rangers débarquent de plein fouet face à ce point d'appui dans les secteurs Charlie et Dog Green, essuyant des tirs croisés dévastateurs qui clouent les survivants au pied de l'escarpement. Ce n'est qu'après plusieurs heures de combats acharnés et l'intervention décisive de destroyers alliés s'approchant au plus près du rivage pour pilonner les ouvrages en béton que la position est neutralisée, permettant l'ouverture cruciale de la première issue carrossable pour les blindés vers l'intérieur des terres.",
    visiter: "Examiner la casemate H667 toujours ancrée sur le bas du versant rocheux, en observant l'embrasure de tir précisément orientée pour balayer le cordon d'estran parallèlement au rivage. Repérer les impacts d'armes automatiques et d'éclats d'obus marquant le béton armé, puis remonter la route du vallon D-1 pour appréhender la difficulté tactique de l'ascension sous le feu des nids de tir surplombants.",
    link: "https://photos.google.com/share/AF1QipP_r-RkUhVBFruOXfc_tByvx5Vje8hgDNED4vVuvCKE6Q2NOmmiqdkWxaQaeFwASQ?key=TklDZmxVZGF4ZTJiaDFUbExPRlJXTkRlLXZzemdB"
  },
  {
    id: "saint_laurent_sur_mer_monument_signal_omaha",
    name: "Saint-Laurent-sur-Mer - Monument Signal d'Omaha Beach",
    country: "France",
    continent: "Europe",
    flag: "🇫🇷",
    region_admin: "Normandie",
    department: "Calvados (14)",
    subdiv: "Saint-Laurent-sur-Mer",
    altitude: 2,
    is_island: false,
    island_name: "",
    transport: "a_pied",
    era_group: "contemporain",
    era_label: "Monument Commémoratif du Débarquement Allié",
    century: "XXe siècle (1956)",
    category: "star",
    counts: {},
    lat: 49.370755,
    lng: -0.879663,
    image: "https://lh3.googleusercontent.com/pw/AP1GczOhIeKo618I67HADx33gmpnVSvChiMbV8RzlBObWtdYnalDREQvOQY-qezfqTfOPatLwYbr1Gmb6Ps6eZzRPmkz3rw0U0RC4gbKu--ZoTkw1hjbxdrQOpj0HlcQ9L_YR4nk4dXnQZdZ4FvQqXzCoDDfiQ=w1379-h919-s-no-gm?authuser=0",
    description: "Érigé face au large sur l'esplanade du secteur central d'Omaha Beach, au débouché du vallon des Moulins (issue D-3), le monument Signal commémore le sacrifice héroïque des forces armées américaines ayant débarqué sur ce littoral surnommé « Bloody Omaha » (Omaha la sanglante). Inauguré dans les années 1950 sous l'égide du Comité du Débarquement, cet ouvrage monumental en pierre calcaire blanche et granit se dresse directement sur les restes nivelés d'un imposant bunker allemand du mur de l'Atlantique, symbolisant de manière tangible la victoire des démocraties sur l'occupation nazie. La stèle principale, ornée de bas-reliefs et de textes commémoratifs bilingues, rend hommage aux combattants des 1re et 29e divisions d'infanterie des États-Unis qui franchirent sous une grêle de balles la vaste zone découverte à marée basse le 6 juin 1944. À quelques mètres sur le sable de l'estran se déploie la sculpture monumentale « Les Braves », créée en 2004 par l'artiste Anilore Banon, dont les ailes d'acier inoxydable élancées vers le ciel renforcent la solennité de ce haut lieu de mémoire internationale.",
    visiter: "Monter sur l'esplanade dallée entourant la stèle pour déchiffrer les inscriptions gravées et examiner la structure du bunker allemand servant de socle à l'édifice mémoriel. Descendre directement sur le sable à marée basse afin de contempler la sculpture monumentale des Braves se découpant contre l'horizon marin, puis balayer du regard les coteaux côtiers pour visualiser l'axe d'assaut des troupes américaines venues de la mer.",
    link: "https://photos.google.com/share/AF1QipP_r-RkUhVBFruOXfc_tByvx5Vje8hgDNED4vVuvCKE6Q2NOmmiqdkWxaQaeFwASQ?key=TklDZmxVZGF4ZTJiaDFUbExPRlJXTkRlLXZzemdB"
  },
  {
    id: "saint_laurent_sur_mer_omaha_wn65",
    name: "Saint-Laurent-sur-Mer - Omaha Beach (Wn 65)",
    country: "France",
    continent: "Europe",
    flag: "🇫🇷",
    region_admin: "Normandie",
    department: "Calvados (14)",
    subdiv: "Saint-Laurent-sur-Mer",
    altitude: 10,
    is_island: false,
    island_name: "",
    transport: "a_pied",
    era_group: "contemporain",
    era_label: "Poste Fortifié & Verrou du Ravin du Ruquet",
    century: "XXe siècle (1944)",
    category: "star",
    counts: {},
    lat: 49.364537,
    lng: -0.863647,
    image: "https://lh3.googleusercontent.com/pw/AP1GczOuEjc1kU_9k819nG4R_Awfr89R2KbR7_RY5R1fUB9PZb4IsIjfaKRs3Vy3xDXiQajLq6CP7pldY2B3R_umRwUg5RBpn0DfieD3AKfCROO1xMaTqGVR-8dV_0_xcqdt7kZ-Fkykvgy06gbS46UyZBEsbw=w1379-h919-s-no-gm?authuser=0",
    description: "Positionné à flanc de falaise pour barrer le vallon du Ruquet (sortie E-1), le Widerstandsnest 65 constituait l'un des bastions défensifs les plus meurtriers et stratégiques du secteur Easy Red d'Omaha Beach. Conçu pour protéger cette brèche naturelle permettant aux véhicules de gravir le plateau calcaire, l'ouvrage s'articulait autour d'une massive casemate en béton armé armée d'un canon antichar de cinquante millimètres tirant en flanquement de la grève, complétée par un abri pour troupe Regelbau 501, des tranchées de tir et des emplacements pour mortiers. Le matin du Jour J, les vagues d'assaut du 16e régiment d'infanterie de la 1re division américaine (la « Big Red One ») subissent ici un carnage effroyable, prises sous le feu croisé incessant des tireurs abrités dans le flanc du coteau. La reddition de la garnison allemande du Wn 65, survenue vers 10 h 30 grâce à l'infiltration audacieuse de petits groupes d'infanterie appuyés par les tirs précis de chars Sherman ayant réussi à atteindre la plage, constitue le véritable tournant de la bataille sur Omaha Beach, permettant au génie militaire d'aménager dès l'après-midi la route principale d'évacuation et de ravitaillement.",
    visiter: "S'approcher de la casemate en béton enchâssée dans la végétation du coteau pour observer son créneau de tir dirigé latéralement vers l'estran de la plage. Suivre le sentier serpentant à flanc de colline pour repérer les vestiges des tranchées de communication et des encuvements secondaires, tout en contemplant la vue plongeante sur l'accès carrossable du Ruquet et l'étendue de sable doré.",
    link: "https://photos.google.com/share/AF1QipP_r-RkUhVBFruOXfc_tByvx5Vje8hgDNED4vVuvCKE6Q2NOmmiqdkWxaQaeFwASQ?key=TklDZmxVZGF4ZTJiaDFUbExPRlJXTkRlLXZzemdB"
  },
  {
    id: "colleville_sur_mer_overlord_museum",
    name: "Colleville-sur-Mer - Overlord Museum",
    country: "France",
    continent: "Europe",
    flag: "🇫🇷",
    region_admin: "Normandie",
    department: "Calvados (14)",
    subdiv: "Colleville-sur-Mer",
    altitude: 68,
    is_island: false,
    island_name: "",
    transport: "route",
    era_group: "contemporain",
    era_label: "Musée Militaire & Collections Blindées du Jour J",
    century: "XXIe siècle (2013)",
    category: "musee",
    counts: {},
    lat: 49.348257,
    lng: -0.856258,
    image: "https://lh3.googleusercontent.com/pw/AP1GczP3ytC7wD3dpFB_BuxaXfKjfIbFcgsv9Y9EKUd2LcmzmmmrzYKwm0iJzrx8Z5ywQnVxeHpiGgUVSD4flVX0pHuhEDMqA4iQdxa0Ji4SaLVuDgQatPTaul1q6-Cr12J_buTiIhir1RigqQv0Kw0eYg03mQ=w1379-h919-s-no-gm?authuser=0",
    description: "Implanté au carrefour d'accès menant au cimetière américain de Colleville-sur-Mer, l'Overlord Museum abrite l'une des plus exceptionnelles collections privées de matériel militaire consacrées à l'opération Overlord et à la bataille de Normandie. Fruit de plus de quarante années de recherches et d'acquisitions menées par Michel Leloup, témoin direct des combats de 1944, l'établissement déploie sur plus de deux mille mètres carrés d'exposition couverte une muséographie immersive remarquable. Le parcours présente des dioramas à l'échelle un reconstituant des scènes de combat réalistes, combinant mannequins en uniformes d'époque d'une rigoureuse authenticité, effets personnels et véhicules lourds entièrement restaurés dans leur état de marche d'origine. Les collections rassemblent plus de quarante blindés, canons et véhicules de transport alliés et allemands, parmi lesquels un rare char Sherman M4, des engins chenillés semi-automoteurs, des véhicules de reconnaissance, des barges fluviales ainsi qu'une bombe volante V1 sur sa rampe. L'exposition s'attache à retracer chronologiquement la planification de l'assaut maritime et aéroporté du 6 juin jusqu'à l'anéantissement de la VIIe armée allemande dans la poche de Falaise-Chambois à la fin du mois d'août 1944.",
    visiter: "Déambuler dans les grands halls d'exposition pour examiner au plus près les engins blindés rares et détailler l'équipement tactique présenté dans les vitrines thématiques. Observer la scénographie travaillée des dioramas qui intègre des gravats, des façades normandes reconstituées et des véhicules en situation de combat. Terminer la visite en contournant l'esplanade extérieure où sont exposés des pièces d'artillerie lourde, des blindés et un imposant canon antiaérien allemand de quatre-vingt-huit millimètres.",
    link: "https://photos.google.com/share/AF1QipP_r-RkUhVBFruOXfc_tByvx5Vje8hgDNED4vVuvCKE6Q2NOmmiqdkWxaQaeFwASQ?key=TklDZmxVZGF4ZTJiaDFUbExPRlJXTkRlLXZzemdB"
  },
  {
    id: "colleville_sur_mer_memorial_cimetiere_americain",
    name: "Colleville-sur-Mer - Mémorial du Cimetière Américain",
    country: "France",
    continent: "Europe",
    flag: "🇫🇷",
    region_admin: "Normandie",
    department: "Calvados (14)",
    subdiv: "Colleville-sur-Mer",
    altitude: 54,
    is_island: false,
    island_name: "",
    transport: "a_pied",
    era_group: "contemporain",
    era_label: "Colonnade Mémorielle & Jardin des Disparus",
    century: "XXe siècle (1956)",
    category: "star",
    counts: {},
    lat: 49.359237,
    lng: -0.853226,
    image: "https://lh3.googleusercontent.com/pw/AP1GczOZgMabZ98Heb8baVOk7TY9pzZXJBNLdoMPUpj93IzttFwldZbWR18H1zj1oBAZe7qPgoR4Y-DnsOpAZUX6lmFEeVzfkX9D827xH1S_6Uqf91p2_0EYv1UamxAPhCG-ZnD1X6q3B8i5Io7RQWg0XM3YOg=w1379-h919-s-no-gm?authuser=0",
    description: "Dominant la perspective orientale du Normandy American Cemetery and Memorial de Colleville-sur-Mer, ce mémorial solennel a été conçu par les architectes new-yorkais Harbeson, Hough, Livingston et Larson. L'ensemble architectural s'articule autour d'une monumentale colonnade semi-circulaire en calcaire du Jura d'inspiration néoclassique, enserrant une vaste esplanade de granit au centre de laquelle trône une majestueuse statue en bronze haute de plus de sept mètres. Réalisée par le sculpteur américain Donald De Lue, cette œuvre allégorique intitulée « L'Esprit de la jeunesse américaine s'élevant des flots » personnifie le sacrifice et la bravoure des milliers de jeunes soldats tombés sur les plages normandes. Les deux loggias encadrant la colonnade abritent de monumentales cartes militaires en émail grand feu et mosaïque de pierres colorées, détaillant avec précision le plan stratégique des opérations aéroportées, les convois du Débarquement et le déroulement de la bataille de Normandie. À l'arrière de l'hémicycle s'étend le paisible Jardin des Disparus, constitué d'un mur en arc de cercle gravé des noms de mille cinq cent cinquante-sept soldats américains portés disparus au combat et dont les corps n'ont jamais pu être retrouvés.",
    visiter: "Avancer au centre de l'hémicycle pour admirer la dynamique de la statue en bronze de Donald De Lue se reflétant dans le grand bassin miroir d'eau qui lui fait face. Détailler sous les loggias latérales les immenses cartes murales polychromes expliquant les phases tactiques du Débarquement naval et des opérations aériennes. Parcourir avec recueillement le Jardin des Disparus à l'arrière de la colonnade pour lire les noms gravés dans la pierre calcaire des soldats portés disparus.",
    link: "https://photos.google.com/share/AF1QipP_r-RkUhVBFruOXfc_tByvx5Vje8hgDNED4vVuvCKE6Q2NOmmiqdkWxaQaeFwASQ?key=TklDZmxVZGF4ZTJiaDFUbExPRlJXTkRlLXZzemdB"
  },
  {
    id: "colleville_sur_mer_visitor_center",
    name: "Colleville-sur-Mer - Centre d'Accueil des Visiteurs",
    country: "France",
    continent: "Europe",
    flag: "🇫🇷",
    region_admin: "Normandie",
    department: "Calvados (14)",
    subdiv: "Colleville-sur-Mer",
    altitude: 53,
    is_island: false,
    island_name: "",
    transport: "a_pied",
    era_group: "contemporain",
    era_label: "Architecture Contemporaine & Centre d'Interprétation Mémoriel",
    century: "XXIe siècle (2007)",
    category: "musee",
    counts: {},
    lat: 49.358607,
    lng: -0.851414,
    image: "https://lh3.googleusercontent.com/pw/AP1GczNZDLvUucm5jfycj3BNSFKFTi4De9bQX5H3FT79I0qYjCGNK5AbzyguuRbTJvJGqTGgygu7ycTyl88_mIBvRpOS5FVt_wWLSOgoZCXNGkKnsLYeruOaCF59IYYXhmGcmZs7dhML_Gexsj4fEeeQmd2oZg=w1379-h919-s-no-gm?authuser=0",
    description: "Inauguré en juin 2007 par l'American Battle Monuments Commission (ABMC) à l'occasion du 63e anniversaire du Débarquement, le Visitor Center du cimetière américain de Colleville-sur-Mer sert de seuil d'introduction historique et pédagogique au site funéraire. Conçu selon des lignes architecturales contemporaines épurées mêlant baies vitrées monumentales, parois de calcaire blond et structures d'acier sombre, l'édifice s'intègre discrètement dans le paysage boisé du plateau littoral sans troubler le recueillement de la nécropole. Les galeries intérieures déploient une exposition permanente d'une grande rigueur documentaire, articulée autour de récits de vie individuels, d'objets militaires authentiques, de lettres de soldats et de témoignages audiovisuels poignants. Le parcours explicite la genèse de l'opération Overlord, les enjeux géopolitiques de la libération de l'Europe occidentale et l'ampleur sans précédent du soutien logistique engagé par les États-Unis. La muséographie met tout particulièrement en lumière le courage des combattants d'Omaha Beach et des rangers de la pointe du Hoc, offrant une contextualisation indispensable avant d'accéder aux rangées silencieuses des croix de marbre blanc.",
    visiter: "Franchir le pavillon d'accueil pour découvrir le parcours muséographique jalonné d'installations interactives, de films d'archives d'époque et d'objets personnels ayant appartenu aux soldats inhumés sur le site. Observer depuis la grande baie vitrée d'extrémité la vue en perspective s'ouvrant sur les bosquets bordant l'allée centrale du cimetière. S'attarder devant le mur mémorial diffusant en continu les photographies et biographies de combattants avant de sortir vers le parc commémoratif.",
    link: "https://photos.google.com/share/AF1QipP_r-RkUhVBFruOXfc_tByvx5Vje8hgDNED4vVuvCKE6Q2NOmmiqdkWxaQaeFwASQ?key=TklDZmxVZGF4ZTJiaDFUbExPRlJXTkRlLXZzemdB"
  },
  {
    id: "colleville_sur_mer_cimetiere_americain",
    name: "Colleville-sur-Mer - Cimetière Américain de Normandie",
    country: "France",
    continent: "Europe",
    flag: "🇫🇷",
    region_admin: "Normandie",
    department: "Calvados (14)",
    subdiv: "Colleville-sur-Mer",
    altitude: 53,
    is_island: false,
    island_name: "",
    transport: "a_pied",
    era_group: "contemporain",
    era_label: "Nécropole Militaire & Sanctuaire International",
    century: "XXe siècle (1956)",
    category: "star",
    counts: {},
    lat: 49.359951,
    lng: -0.85608,
    image: "https://lh3.googleusercontent.com/pw/AP1GczNcPmNU7yVhTziWh3vP7pTlI4rVBO3ixdflmBPeYFywT4kfbRYG12FM6jADerO_sgm9KTv_mNeRgZt11cKLxMGExENamHuu1BT4B7GonzMSNEzdrqVqyAance-s3_W_khzwZXwNw0rMJyt2CKbn_dejXQ=w1379-h919-s-no-gm?authuser=0",
    description: "Établi au sommet de la falaise dominant Omaha Beach, sur un domaine de soixante-dix hectares concédé à perpétuité par la France aux États-Unis, le cimetière américain de Colleville-sur-Mer est la nécropole militaire américaine la plus visitée au monde. Aménagé dès le 8 juin 1944 sous le nom de cimetière provisoire de Saint-Laurent par les services des sépultures de la First Army, le site définitif a été inauguré en 1956 après des travaux paysagers colossaux menés par les architectes Markley Stevenson et Harbeson. Il rassemble les sépultures de neuf mille trois cent quatre-vingt-huit soldats américains tombés lors du Débarquement et des opérations de la bataille de Normandie, ainsi que quatre femmes membres des services auxiliaires civils et militaires. Les tombes sont matérialisées par de strictes stèles immaculées en marbre blanc de Carrare, taillées sous la forme de croix latines ou d'étoiles de David pour les défunts de confession juive, parfaitement alignées sur une pelouse irréprochable rythmée de pins parasols et de massifs fleuris. Parmi les personnalités inhumées figurent le général de brigade Theodore Roosevelt Jr, fils du président Theodore Roosevelt et médaillé d'honneur du Congrès, ainsi que les frères Niland, dont le destin tragique a inspiré le scénario du film « Il faut sauver le soldat Ryan ».",
    visiter: "Déambuler en silence le long des allées géométriques divisées en dix carrés funéraires pour apprécier l'alignement visuel parfait des milliers de croix de marbre blanc se détachant sur le vert des pelouses. Rejoindre la table d'orientation aménagée en belvédère au bord du plateau pour embrasser d'un regard toute l'étendue de la plage d'Omaha Beach en contrebas. Repérer les sépultures remarquables des récipiendaires de la Medal of Honor signalées par des lettres gravées et dorées à l'or fin.",
    link: "https://photos.google.com/share/AF1QipP_r-RkUhVBFruOXfc_tByvx5Vje8hgDNED4vVuvCKE6Q2NOmmiqdkWxaQaeFwASQ?key=TklDZmxVZGF4ZTJiaDFUbExPRlJXTkRlLXZzemdB"
  },
  {
    id: "colleville_sur_mer_chapelle_du_cimetiere",
    name: "Colleville-sur-Mer - Chapelle du Cimetière Américain",
    country: "France",
    continent: "Europe",
    flag: "🇫🇷",
    region_admin: "Normandie",
    department: "Calvados (14)",
    subdiv: "Colleville-sur-Mer",
    altitude: 53,
    is_island: false,
    island_name: "",
    transport: "a_pied",
    era_group: "contemporain",
    era_label: "Édifice Religieux Mémorial & Mosaïque de la Paix",
    century: "XXe siècle (1956)",
    category: "star",
    counts: {},
    lat: 49.360413,
    lng: -0.857961,
    image: "https://lh3.googleusercontent.com/pw/AP1GczMA83DHSHpiEAXsaNlxONjjccUkp-zEmkMA4j18TXizhS4BgyyoJdH7EKOW2u5BUSQ3SXClgaOrOudN7_rlrziwG9ljFePhWm1PDTa3NlmwSSX_SmuvlZ50EYsEn8xJ6siSw4j_9vvVHfVxb5kp5_Ghvw=w613-h919-s-no-gm?authuser=0",
    description: "Érigée au cœur géographique de la nécropole militaire, à l'intersection de l'allée centrale bordée d'arbres et de l'axe transversal séparant les carrés de tombes, la chapelle commémorative s'élève comme un sanctuaire de recueillement et de paix universelle. Conçue selon un plan circulaire élégant et sobre en calcaire doré du Jura par les architectes Harbeson, Hough, Livingston et Larson, la rotonde est coiffée d'un dôme bas couronné d'une flèche de bronze. L'intérieur circulaire, baigné par la lumière douce filtrant à travers des vitraux translucides épurés, abrite un autel monolithique en marbre noir des Pyrénées gravé de l'inscription biblique « Je leur donne la vie éternelle et elles ne périront jamais ». Le joyau artistique de la chapelle réside dans son plafond en mosaïque polychrome conçu par l'artiste américain Leon Kroll. Cette immense composition circulaire allégorique illustre la déesse de la Liberté bénissant la jeunesse américaine prête à traverser les mers pour secourir la France et l'Europe enchaînées par la tyrannie, tandis qu'au centre resplendit la colombe de la paix auréolée de gloire céleste.",
    visiter: "S'approcher de la rotonde circulaire en observant son appareillage de pierre claire encadré par les perspectives rectilignes des carrés de tombes. Pénétrer à l'intérieur pour contempler la mosaïque monumentale du dôme conçue par Leon Kroll et s'imprégner de ses détails allégoriques symbolisant l'amitié franco-américaine. Marquer un temps d'arrêt devant l'autel de marbre noir des Pyrénées et détailler les devises patriotiques et spirituelles sculptées sur le pourtour intérieur du tambour.",
    link: "https://photos.google.com/share/AF1QipP_r-RkUhVBFruOXfc_tByvx5Vje8hgDNED4vVuvCKE6Q2NOmmiqdkWxaQaeFwASQ?key=TklDZmxVZGF4ZTJiaDFUbExPRlJXTkRlLXZzemdB"
  },
  {
    id: "bayeux_pont_place_aux_pommes",
    name: "Bayeux - Pont de la Place aux Pommes",
    country: "France",
    continent: "Europe",
    flag: "🇫🇷",
    region_admin: "Normandie",
    department: "Calvados (14)",
    subdiv: "Bayeux",
    altitude: 36,
    is_island: false,
    island_name: "",
    transport: "a_pied",
    era_group: "medieval",
    era_label: "Franchissement Fluvial & Rives Pittoresques de l'Aure",
    century: "XVe siècle",
    category: "pont",
    counts: {},
    lat: 49.277343,
    lng: -0.700026,
    image: "https://lh3.googleusercontent.com/pw/AP1GczM9QSY-2AF9Wng2DJhJB34kkmoO3w5o2ydC5Vsyl06bOpFJ-MAFDC60OQvycv43CSjeTki7V0mkBP5Oywqn5fcYViv-WY4CWd3nlKV_il5sc9DJ-UFF_VrpCBvfDqf2UogRrwRYAsNJlTItLSC_2Yc33g=w1379-h919-s-no-gm?authuser=0",
    description: "Ouvrage de pierre franchissant l'Aure à la jonction entre le quartier médiéval des tanneurs et l'ancienne place commerciale aux Pommes, ce pont en maçonnerie témoigne du rôle primordial du cours d'eau dans le développement artisanal et urbain de Bayeux. Bâti en moellons de calcaire du Bessin avec des arches surbaissées soigneusement appareillées, il reliait jadis les marchés de primeurs et de fruits de la basse ville aux ateliers de traitement du cuir, de draperie et de teinturerie établis au fil de la rivière. L'Aure constituait en effet une voie d'énergie motrice et de travail essentielle au Moyen Âge et sous l'Ancien Régime, comme en attestent les nombreux biefs, déversoirs et canaux de dérivation visibles dans les parages immédiats. Depuis les parapets du pont, le regard embrasse une perspective pittoresque sur les maisons à pan de bois et façades de pierre dont les soubassements plongent directement dans l'eau claire, ainsi que sur les anciens lavoirs et passages voûtés en encorbellement. Préservé des destructions de 1944 grâce à la libération précoce de la ville dès le 7 juin, ce secteur fluvial a conservé son charme bucolique et sa structure viaire médiévale d'origine.",
    visiter: "S'accouder au parapet de pierre pour contempler le reflet des façades anciennes dans l'eau de l'Aure et observer les anciens déversoirs de retenue d'eau. Emprunter la promenade aménagée le long des berges pour apprécier les arches de pierre du pont vues d'en bas et découvrir les passerelles fleuries reliant les maisons d'habitation. Poursuivre vers la place aux Pommes pour repérer les belles demeures bourgeoises des XVIIe et XVIIIe siècles ceinturant l'esplanade pavée.",
    link: "https://photos.google.com/share/AF1QipP_r-RkUhVBFruOXfc_tByvx5Vje8hgDNED4vVuvCKE6Q2NOmmiqdkWxaQaeFwASQ?key=TklDZmxVZGF4ZTJiaDFUbExPRlJXTkRlLXZzemdB"
  },
  {
    id: "bayeux_rue_des_cuisiniers",
    name: "Bayeux - Rue des Cuisiniers",
    country: "France",
    continent: "Europe",
    flag: "🇫🇷",
    region_admin: "Normandie",
    department: "Calvados (14)",
    subdiv: "Bayeux",
    altitude: 48,
    is_island: false,
    island_name: "",
    transport: "a_pied",
    era_group: "medieval",
    era_label: "Artère Médiévale & Demeures à Pans de Bois",
    century: "XIVe siècle",
    category: "habitation",
    counts: {},
    lat: 49.277278,
    lng: -0.702894,
    image: "https://lh3.googleusercontent.com/pw/AP1GczNzMK0EvhIKsJmkTQ6wxsBV8jChnUkZW0RdEa5XSXeXVIPsOJV3xnr3_qXqgP9T0_5rhuYeGrIkbNwixM0BhAX1AOvjxmuoV9xu12GdIGf0DfSrHz9-fn9yCdfVuKlupDtSucLZ5nmkO59HtZjIc0V9oQ=w613-h919-s-no-gm?authuser=0",
    description: "Tracée au cœur du noyau historique intramuros de Bayeux, à l'ouest du chevet de la cathédrale, la rue des Cuisiniers tire son appellation des confréries et échoppes de métiers de bouche qui s'y installèrent au Moyen Âge pour approvisionner le puissant chapitre canonial et la cour épiscopale. L'artère constitue un remarquable conservatoire de l'architecture civile urbaine du XIVe au XVIIIe siècle, épargnée par les combats de la Libération de juin 1944. Elle présente un alignement continu de maisons de maîtres et de demeures marchandes illustrant l'évolution des techniques constructives normandes : soubassements en pierre calcaire de Caen, élévations supérieures à pans de bois hourdés d'argile ou de briques en arête-de-poisson, et remarquables encorbellements successifs permettant de gagner de l'espace sur l'étroit tracé de la voie publique. Plusieurs de ces édifices conservent des sablières sculptées, des poteaux corniers ouvragés à motifs végétaux ou grotesques et des toitures aiguës percées de lucarnes traditionnelles. Reliant le quartier des halles à l'ancien évêché, la rue illustre l'intense vie commerçante et la richesse patrimoniale préservée de la première ville importante libérée de France continentale.",
    visiter: "Arpenter lentement la ruelle pavée en levant les yeux vers les étages supérieurs pour admirer les structures en encorbellement et les décors sculptés sur les colombages en chêne. Remarquer au fil de la progression les détails ornementaux des portes anciennes, heurtoirs en ferronnerie et encadrements de fenêtres chanfreinés taillés dans le calcaire du Bessin. Profiter de l'échappée visuelle spectaculaire qu'offre l'extrémité de la rue sur les tours et la flèche de la cathédrale Notre-Dame.",
    link: "https://photos.google.com/share/AF1QipP_r-RkUhVBFruOXfc_tByvx5Vje8hgDNED4vVuvCKE6Q2NOmmiqdkWxaQaeFwASQ?key=TklDZmxVZGF4ZTJiaDFUbExPRlJXTkRlLXZzemdB"
  },
  {
    id: "bayeux_musee_art_et_histoire_baron_gerard",
    name: "Bayeux - Musée d'Art et d'Histoire Baron Gérard (MAHB)",
    country: "France",
    continent: "Europe",
    flag: "🇫🇷",
    region_admin: "Normandie",
    department: "Calvados (14)",
    subdiv: "Bayeux",
    altitude: 40,
    is_island: false,
    island_name: "",
    transport: "a_pied",
    era_group: "renaissance",
    era_label: "Ancien Palais Épiscopal & Collections Patrimoniales",
    century: "XVIe siècle",
    category: "musee",
    counts: {},
    lat: 49.276105,
    lng: -0.70365,
    image: "https://lh3.googleusercontent.com/pw/AP1GczMZaswXUKwLO5EJy3rZMt-oafOGEPIvCZanRTkqMlmt_M90XgcCr57Nukv14RZcCqCo5Mqg-aNMD_ImIpGvqLtKtXQhQog7tqRIkxaw1lxbVv9KWZ7krIjBEVQlppKvH0EIdsoKRRY9OE7a6xBYXpK-RA=w1379-h919-s-no-gm?authuser=0",
    description: "Installé dans le cadre grandiose de l'ancien palais des évêques de Bayeux, adossé au flanc nord de la cathédrale Notre-Dame, le musée d'Art et d'Histoire Baron Gérard (MAHB) occupe un ensemble monumental édifié du XIe au XVIIIe siècle. Le corps de logis principal conserve des éléments majeurs de la Renaissance et de l'âge classique, dont une remarquable chapelle castrale ornée de peintures murales maniéristes du début du XVIIe siècle commandées par l'évêque Arnaud d'Ossat. Réaménagé au début du XXIe siècle avec une scénographie contemporaine élégante, le musée offre un parcours chronologique dense retraçant l'histoire de la création artistique et du territoire normand, depuis la préhistoire jusqu'à l'art moderne. Les collections rassemblent de prestigieux vestiges archéologiques gallo-romains issus de l'antique Augustodurum, des chefs-d'œuvre de la peinture européenne signés Philippe de Champaigne, François Boucher ou Gustave Caillebotte, ainsi qu'un fonds exceptionnel consacré aux arts décoratifs locaux. Le musée est particulièrement réputé pour sa collection d'excellence de dentelle aux fuseaux de Bayeux et ses ensembles complets de pièces de porcelaine de la manufacture de Bayeux, témoignant du rayonnement industriel et artistique de la cité aux XVIIIe et XIXe siècles.",
    visiter: "Admirer la cour d'honneur pavée de l'évêché dominée par l'ombre majestueuse du platane de la Liberté planté en 1797. Parcourir les salles archéologiques souterraines révélant les fondations antiques avant de monter dans les étages pour contempler les toiles de maîtres de la Renaissance au XIXe siècle. Prendre le temps d'observer sous vitrine les pièces raffinées de dentelle au point de Bayeux et les délicates créations de porcelaine polychrome arborant des décors d'inspiration orientale.",
    link: "https://photos.google.com/share/AF1QipP_r-RkUhVBFruOXfc_tByvx5Vje8hgDNED4vVuvCKE6Q2NOmmiqdkWxaQaeFwASQ?key=TklDZmxVZGF4ZTJiaDFUbExPRlJXTkRlLXZzemdB"
  },
  {
    id: "bayeux_cathedrale_notre_dame",
    name: "Bayeux - Cathédrale Notre-Dame",
    country: "France",
    continent: "Europe",
    flag: "🇫🇷",
    region_admin: "Normandie",
    department: "Calvados (14)",
    subdiv: "Bayeux",
    altitude: 40,
    is_island: false,
    island_name: "",
    transport: "a_pied",
    era_group: "medieval",
    era_label: "Chef-d'œuvre de l'Art Roman & Gothique Rayonnant",
    century: "XIe siècle (1077)",
    category: "religieux",
    counts: {},
    lat: 49.275601,
    lng: -0.703713,
    image: "https://lh3.googleusercontent.com/pw/AP1GczOys-41G6vwCHEueGLNkG5VVo7NicR7_E3vF96STd2sR7ZS9gnbxR0rjpw5GvJM1Lh_9uvyEbzrWFedg_xZSC67d66GQ8pcRujieyxPrSlN2EdTJFDGmHz9D8GRrA4yVQFy77wPk_ee0UzLjjudHIXfmw=w1379-h919-s-no-gm?authuser=0",
    description: "Édifiée au sommet de la colline historique dominant l'Aure, la cathédrale Notre-Dame de Bayeux est un joyau exceptionnel illustrant la fusion harmonieuse de l'art roman normand et de l'architecture gothique rayonnante. Consacrée le 14 juillet 1077 par l'évêque Odon de Conteville en présence de son demi-frère Guillaume le Conquérant, l'église romane primitive fut conçue pour servir d'écrin à la célèbre tapisserie de Bayeux, traditionnellement suspendue dans la nef lors des grandes solennités liturgiques. De cette époque subsistent la majestueuse crypte souterraine, ornée de colonnes à chapiteaux sculptés et de fresques peintes d'anges musiciens du XVe siècle, ainsi que les deux imposantes tours occidentales et les grandes arcades de la nef au décor sculpté de bâtons rompus et de frettes crénelées d'une richesse foisonnante. Reconstruite après les incendies du XIIe siècle, la cathédrale est sublimée au XIIIe siècle par l'érection d'un chœur gothique étourdissant d'élégance, caractérisé par ses triforiums ajourés, ses voûtes sur croisées d'ogives et ses baies élancées inondant le sanctuaire de lumière. Au-dessus de la croisée du transept s'élève la spectaculaire tour lanterne, complétée au XVe siècle dans le style flamboyant puis coiffée au XIXe siècle d'un dôme en cuivre par l'architecte Eugène Viollet-le-Duc.",
    visiter: "Observer depuis le parvis les tours romanes occidentales coiffées de flèches gothiques et les portails sculptés illustrant le Jugement dernier et la vie de Thomas Becket. Pénétrer dans la nef pour détailler les sculptures géométriques des écoinçons romans avant d'admirer la légèreté vertigineuse du chœur gothique du XIIIe siècle. Descendre impérativement dans la crypte du XIe siècle pour contempler les chapiteaux romans primitifs et les peintures murales d'anges musiciens sur les voûtes.",
    link: "https://photos.google.com/share/AF1QipP_r-RkUhVBFruOXfc_tByvx5Vje8hgDNED4vVuvCKE6Q2NOmmiqdkWxaQaeFwASQ?key=TklDZmxVZGF4ZTJiaDFUbExPRlJXTkRlLXZzemdB"
  },
  {
    id: "bayeux_moulin_coisel",
    name: "Bayeux - Moulin Coisel",
    country: "France",
    continent: "Europe",
    flag: "🇫🇷",
    region_admin: "Normandie",
    department: "Calvados (14)",
    subdiv: "Bayeux",
    altitude: 40,
    is_island: false,
    island_name: "",
    transport: "a_pied",
    era_group: "moderne",
    era_label: "Patrimoine Hydraulique & Énergie Fluviale de l'Aure",
    century: "XVIIIe siècle",
    category: "star",
    counts: {},
    lat: 49.273986,
    lng: -0.701074,
    image: "https://lh3.googleusercontent.com/pw/AP1GczOmYMAWCcRiGDuSrNHvNMBI8E9KeVxuCOiB-aiB8dbFdrqYSqqfsmOpwtlj-MCRBvEZbV3o2zj-0nW0JujHRfeR3_GMIydixuZytn4mgc_AOFbn8CwHKi1LrA3znZDvUtaign0ekElRavzXLG8N6bEmQA=w1379-h919-s-no-gm?authuser=0",
    description: "Établi le long d'un bief artificiel dérivé de l'Aure au sud du centre ecclésiastique de Bayeux, le moulin Coisel constitue l'un des rares témoins parfaitement préservés de la longue tradition meunière et hydraulique de la cité bajocasse. Construit en moellons de calcaire local sous une toiture traditionnelle en tuiles et ardoises, ce moulin à eau remonte au XVIIIe siècle, succédant à des installations hydrauliques médiévales attestées dès le Moyen Âge dans les registres du domaine épiscopal. Alimenté par un système ingénieux de vannes de décharge et de vannages de régulation contrôlant le débit du cours d'eau, il utilisait la force motrice de l'Aure pour actionner des roues à aubes destinées à la mouture des céréales et au travail de foulage. À proximité des anciens couvents et ateliers artisanaux du sud de la ville, le site illustre la symbiose séculaire entre l'aménagement hydrographique de la vallée et le développement économique urbain. Soigneusement restauré dans le cadre de la mise en valeur des promenades vertes bordant la rivière, le moulin forme un ensemble bucolique d'une grande valeur paysagère et patrimoniale, à deux pas des rives fleuries traversant la cité médiévale.",
    visiter: "Longer la promenade piétonne aménagée sur les berges de l'Aure pour observer la structure en pierre du moulin et le système de vannes guidant les eaux du bief. Examiner les mécanismes de retenue hydraulique et le bief en pierre où venait s'engouffrer le courant pour actionner la roue. Profiter de la quiétude du cadre végétalisé pour réaliser de superbes clichés du reflet des façades anciennes dans les eaux calmes de la rivière.",
    link: "https://photos.google.com/share/AF1QipP_r-RkUhVBFruOXfc_tByvx5Vje8hgDNED4vVuvCKE6Q2NOmmiqdkWxaQaeFwASQ?key=TklDZmxVZGF4ZTJiaDFUbExPRlJXTkRlLXZzemdB"
  },
  {
    id: "bayeux_musee_tapisserie",
    name: "Bayeux - Musée de la Tapisserie de Bayeux",
    country: "France",
    continent: "Europe",
    flag: "🇫🇷",
    region_admin: "Normandie",
    department: "Calvados (14)",
    subdiv: "Bayeux",
    altitude: 40,
    is_island: false,
    island_name: "",
    transport: "a_pied",
    era_group: "medieval",
    era_label: "Broderie Romanes & Récit de la Conquête de l'Angleterre",
    century: "XIe siècle (1077)",
    category: "musee",
    // unesco_name: "Mémoire du Monde",
    counts: {},
    lat: 49.274405,
    lng: -0.700277,
    image: "https://lh3.googleusercontent.com/pw/AP1GczPCKPWitTbjwX104i_TwDtKdF_q8xsAGoQW2gtf-6UsRuFIyFh3HXtounSpWmNbDvA3XDXkBJXiXtxCyorqVt4ErZEj__UORCB_rRNG5b4oHQmxHO9-j9TBBpfTMcLBPngl1Ssd4_U8HsWJnDZcnGNJBQ=w1225-h919-s-no-gm?authuser=0",
    description: "Aménagé dans l'ancien Grand Séminaire de Bayeux, vaste édifice classique du XVIIe siècle ordonné autour d'une cour solennelle, le musée abrite l'un des trésors artistiques les plus précieux et célèbres du Moyen Âge occidental : la tapisserie de Bayeux, également appelée broderie de la reine Mathilde. Réalisée au cours des années 1070, très probablement sur commande de l'évêque Odon de Conteville pour orner la nouvelle cathédrale Notre-Dame, cette œuvre monumentale inscrite au registre Mémoire du monde de l'UNESCO est en réalité une broderie de fils de laine teints sur une toile de lin longue de près de soixante-dix mètres et haute de cinquante centimètres. Elle relate avec une vivacité narrative stupéfiante les événements conduisant à la conquête normande de l'Angleterre en 1066 par Guillaume le Conquérant, depuis l'expédition d'Harold Godwinson jusqu'à l'affrontement décisif de la bataille d'Hastings. Véritable document historique et sociologique de premier ordre, l'étoffe fourmille de détails réalistes sur l'armement, l'équitation, la navigation maritime, les fortifications castrales et la vie quotidienne du XIe siècle, complétée dans ses bordures supérieure et inférieure par un bestiaire fabuleux et des illustrations de fables d'Ésope.",
    visiter: "Avancer dans la galerie sombre et thermorégulée pour contempler la broderie de lin déployée sur près de 70 mètres derrière sa vitrine blindée sécurisée. Suivre scène par scène le récit brodé pour observer les détails techniques fascinants : la construction de la flotte d'invasion normande, la traversée de la Manche et le choc des cavaliers à Hastings. Monter au premier étage pour visiter l'espace muséographique didactique comprenant la projection d'un film d'analyse historique et des maquettes de drakkars.",
    link: "https://photos.google.com/share/AF1QipP_r-RkUhVBFruOXfc_tByvx5Vje8hgDNED4vVuvCKE6Q2NOmmiqdkWxaQaeFwASQ?key=TklDZmxVZGF4ZTJiaDFUbExPRlJXTkRlLXZzemdB"
  },
  {
    id: "longues_sur_mer_batterie",
    name: "Longues-sur-Mer - Batterie Côtière Allemande",
    country: "France",
    continent: "Europe",
    flag: "🇫🇷",
    region_admin: "Normandie",
    department: "Calvados (14)",
    subdiv: "Longues-sur-Mer",
    altitude: 74,
    is_island: false,
    island_name: "",
    transport: "a_pied",
    era_group: "contemporain",
    era_label: "Batterie d'Artillerie Côtière du Mur de l'Atlantique",
    century: "XXe siècle (1944)",
    category: "star",
    counts: {},
    lat: 49.343384,
    lng: -0.693449,
    image: "https://lh3.googleusercontent.com/pw/AP1GczM8sl84pSl0i-yYu4ys2t3-pyPHTGMnZYRzdAhA4gCq1lyhgPaerez0cPi0txb3j1LHeajf-VLhbHN5xFLNKJDYESsHRi4-AN3g0MGzNH6Re98ECcfAC3Nf-7-1n5qwOZPM_OVBXXzccx28hfwpBOQw3Q=w1380-h919-s-no-gm?authuser=0",
    description: "Édifiée par la Kriegsmarine puis transférée à la Wehrmacht au sommet des falaises littorales dominant la Manche, la batterie d'artillerie de Longues-sur-Mer (codée Wn 48) constitue l'un des ouvrages les plus spectaculaires et les mieux conservés de tout le mur de l'Atlantique en France. Positionnée de façon stratégique à mi-chemin entre les plages d'Omaha Beach et de Gold Beach, elle était armée de quatre redoutables canons de marine à tir rapide de cent cinquante millimètres (15 cm Tbts.K C/36) placés sous d'épaisses casemates en béton armé de type Regelbau M272, dotées d'un blindage d'acier et d'une portée de feu atteignant près de vingt kilomètres. Au lever du jour le 6 juin 1944, la batterie engage un duel d'artillerie d'une rare violence contre les croiseurs alliés HMS Ajax et Georges Leygues, tirant plus d'une centaine d'obus sur les bâtiments de guerre avant d'être réduite au silence par les tirs précis de l'artillerie navale et les bombes aériennes. Le site a conservé l'intégralité de ses quatre casemates en béton, fait unique sur les plages du Débarquement où les pièces d'artillerie d'origine trônent encore dans leurs embrasures, ainsi qu'un poste de direction de tir à deux étages rendu célèbre pour avoir servi de décor au film « Le Jour le plus long ».",
    visiter: "Parcourir le vaste plateau herbeux pour examiner de près les quatre casemates en béton et admirer les imposants canons de marine de 150 mm toujours en place sur leurs affûts d'acier. S'avancer vers le bord de la falaise pour découvrir le poste de direction de tir à deux niveaux semi-enterré et son embrasure d'observation panoramique. Observer les impacts d'obus navals perforants et les éclats de bombes ayant déchiqueté le béton armé lors des pilonnages navals du 6 juin.",
    link: "https://photos.google.com/share/AF1QipP_r-RkUhVBFruOXfc_tByvx5Vje8hgDNED4vVuvCKE6Q2NOmmiqdkWxaQaeFwASQ?key=TklDZmxVZGF4ZTJiaDFUbExPRlJXTkRlLXZzemdB"
  },
  {
    id: "manvieux_cap_manvieux",
    name: "Manvieux - Falaises du Cap Manvieux",
    country: "France",
    continent: "Europe",
    flag: "🇫🇷",
    region_admin: "Normandie",
    department: "Calvados (14)",
    subdiv: "Manvieux",
    altitude: 42,
    is_island: false,
    island_name: "",
    transport: "a_pied",
    era_group: "nature",
    era_label: "Panorama Côtier & Vestiges du Port Mulberry d'Arromanches",
    century: "",
    category: "star",
    counts: {},
    lat: 49.345,
    lng: -0.63983,
    image: "https://lh3.googleusercontent.com/pw/AP1GczPdV35Ga07-cSSeXpeZISBtNjL0IRTutYVN500B9LOi3jxnzqHKYVohVReon5RHetuXhmRg2GvNa6WqvkBMZYsZ6e9wM31NVlAsGRlQlw218ZH3cxSwC9ihRKE9fXXwsln2oEuY5J-eHFhpqjO0jFfdnw=w1379-h919-s-no-gm?authuser=0",
    description: "Culminant à plus de quarante mètres au-dessus du niveau de la mer entre Port-en-Bessin et Arromanches-les-Bains, le cap Manvieux déploie un alignement majestueux de falaises vives taillées dans les calcaires oolithiques et les marnes du Jurassique supérieur du Bessin. Cet éperon naturel offre un belvédère paysager exceptionnel sur la Manche, la Côte de Nacre et la baie de Seine occidentale. Les versants abrupts, soumis à l'érosion constante de la houle et aux embruns salins, abritent une pelouse calcaro-marneuse littorale d'un grand intérêt écologique, colonisée par des espèces floristiques protégées adaptées aux vents violents et servant d'aire de nidification pour de nombreuses colonies d'oiseaux marins tels que le goéland argenté et le fulmar boréal. Sur le plan historique, le sommet du cap Manvieux offre un point de vue stratégique incomparable et direct sur la rade foraine d'Arromanches et les vestiges titanesques du port artificiel Mulberry B (Port Winston). Mis en place par les Alliés dès les jours suivant le 6 juin 1944 pour approvisionner les armées de libération en vivres, munitions et véhicules lourds, ce chef-d'œuvre du génie militaire britannique laisse encore voir à marée basse son imposant demi-cercle de caissons en béton Phoenix immergés au large.",
    visiter: "Emprunter le sentier de grande randonnée des douaniers (GR 223) qui longe le bord supérieur de la falaise herbeuse pour profiter du grand air du large. Braquer le regard vers l'est pour contempler le panorama saisissant sur les caissons Phoenix en béton du port artificiel Mulberry B posés au large de la plage d'Arromanches. Observer la flore rase de falaise et guetter le vol plané des fulmars boréaux nichant dans les failles de la paroi rocheuse calcaire.",
    link: "https://photos.google.com/share/AF1QipP_r-RkUhVBFruOXfc_tByvx5Vje8hgDNED4vVuvCKE6Q2NOmmiqdkWxaQaeFwASQ?key=TklDZmxVZGF4ZTJiaDFUbExPRlJXTkRlLXZzemdB"
  },
  {
    id: "courseulles_sur_mer_juno_beach",
    name: "Courseulles-sur-Mer - Juno Beach",
    country: "France",
    continent: "Europe",
    flag: "🇫🇷",
    region_admin: "Normandie",
    department: "Calvados (14)",
    subdiv: "Courseulles-sur-Mer",
    altitude: 2,
    is_island: false,
    island_name: "",
    transport: "a_pied",
    era_group: "contemporain",
    era_label: "Secteur de Débarquement Canadien & Plage de la Libération",
    century: "XXe siècle (1944)",
    category: "plage",
    counts: {},
    lat: 49.337779,
    lng: -0.469145,
    image: "https://lh3.googleusercontent.com/pw/AP1GczMZquiT_km5ldezxGWeveXfQU_6eBCqvkcpBvioe6KNE9JwUUfZeojmbJpqAhz1EZ2_eIuGgXto3a0AWQE4WL9nQjbk82M63JLd-sscBNJkoTd1MQbV7_nLlMPHr6iLWCQMJRPlo5IA6v8IhAeCLhknLg=w1379-h919-s-no-gm?authuser=0",
    description: "S'étirant le long du littoral de la Côte de Nacre de part et d'autre de l'embouchure de la Seulles, le secteur de Juno Beach constitue l'une des cinq grandes plages de débarquement de Normandie, assignée le 6 juin 1944 à la 3e division d'infanterie et à la 2e brigade blindée canadiennes, appuyées par des commandos britanniques. Bordée d'un cordon dunaire vulnérable et de digues protégeant les stations balnéaires de Courseulles-sur-Mer, Bernières et Saint-Aubin, la zone était lourdement défendue par le réseau allemand de points d'appui côtiers comprenant casemates de tir, canons sous abri et nids de mitrailleuses croisés. Retardées par une marée haute dangereuse dissimulant les récifs et les obstacles de plage piégés, les premières vagues d'assaut canadiennes débarquent sous un feu nourri qui occasionne des pertes sévères dans les premiers instants. Grâce à l'engagement décisif des chars amphibies duplex drive et au courage héroïque des fantassins des régiments du Royal Winnipeg Rifles, des Regina Rifles et de la North Shore, les défenses allemandes sont enfoncées en quelques heures. À la fin de la journée du 6 juin, les troupes canadiennes ont réalisé la percée territoriale la plus profonde de tous les secteurs alliés, s'avançant de plus de dix kilomètres vers l'intérieur des terres en direction de l'axe routier Caen-Bayeux.",
    visiter: "Marcher sur l'immense estran de sable découvert à marée basse pour prendre la mesure du glacis à découvert que durent traverser les vagues d'assaut canadiennes le 6 juin 1944. Découvrir sur la dune le Centre Juno Beach à l'architecture géométrique remarquable et le char Sherman amphibie exposé sur l'esplanade. Observer à proximité immédiate de la jetée du port les bunkers allemands préservés et les stèles rendant hommage aux différents régiments d'infanterie du Canada.",
    link: "https://photos.google.com/share/AF1QipP_r-RkUhVBFruOXfc_tByvx5Vje8hgDNED4vVuvCKE6Q2NOmmiqdkWxaQaeFwASQ?key=TklDZmxVZGF4ZTJiaDFUbExPRlJXTkRlLXZzemdB"
  },
 {
    id: "caen_chateau",
    name: "Caen - Château Ducal",
    country: "France",
    continent: "Europe",
    flag: "🇫🇷",
    region_admin: "Normandie",
    department: "Calvados (14)",
    subdiv: "Caen",
    altitude: 29,
    is_island: false,
    island_name: "",
    transport: "a_pied",
    era_group: "medieval",
    era_label: "Forteresse Ducale & Résidence des Ducs de Normandie",
    century: "XIe siècle (1060)",
    category: "chateau",
    counts: {},
    lat: 49.187161,
    lng: -0.363092,
    image: "https://lh3.googleusercontent.com/pw/AP1GczPwMeOlN2hghhfFMthOB7kcVP7h-ovzWNgjBNXqWJA_T_C3c02-uja0nC7S7upJA-KPBoOwprIpobgiHMAhTOHDJmJ14nU0tBYZQZyrrD6V-QBwP2nWKwvxEsdhHb3Ze-s8VERAdFrT5g3qbaYOPhjAVw=w1379-h919-s-no-gm?authuser=0",
    description: "Fondée vers 1060 par Guillaume le Conquérant sur un promontoire calcaire dominant la vallée de l'Orne, cette vaste forteresse s'étend sur plus de cinq hectares, ce qui en fait l'une des plus grandes enceintes médiévales fortifiées d'Europe. Conçu à l'origine pour affirmer l'autorité ducale sur la plaine de Caen, le site est profondément remanié au fil des siècles, notamment par Henri Ier Beauclerc qui y fait bâtir un imposant donjon roman carré et la célèbre salle de l'Échiquier de Normandie, remarquable témoin de l'architecture civile anglo-normande du XIIe siècle. Sous la domination des rois de France, Philippe Auguste ordonne le creusement de fossés monumentaux et la construction de la chemise du donjon, avant que la guerre de Cent Ans n'entraîne la modernisation des défenses, matérialisée par la porte Saint-Pierre flanquée de puissantes tours à mâchicoulis et la barbacane de la porte des Champs. Transformé en caserne militaire après la Révolution, le château subit de lourds bombardements lors des combats acharnés de l'été 1944. Les destructions des casernements modernes ont toutefois permis de dégager la cour intérieure et de mettre au jour les structures médiévales originelles. Aujourd'hui restauré, le site forme le cœur patrimonial de la ville, abritant dans son écrin de remparts en pierre de Caen le musée des Beaux-Arts et le musée de Normandie.",
    visiter: "Gravir les escaliers menant au chemin de ronde des remparts pour profiter d'un panorama circulaire exceptionnel sur les toits de la ville et les flèches des églises médiévales. Franchir la porte fortifiée des Champs avec son châtelet défensif et sa barbacane avant de traverser la vaste cour haute arborée. S'arrêter devant l'austère salle romane de l'Échiquier de Normandie afin d'en observer les baies géminées, puis explorer les vestiges archéologiques consolidés du donjon de Philippe Auguste et les jardins botaniques aménagés au pied des courtines.",
    link: "https://photos.google.com/share/AF1QipP_r-RkUhVBFruOXfc_tByvx5Vje8hgDNED4vVuvCKE6Q2NOmmiqdkWxaQaeFwASQ?key=TklDZmxVZGF4ZTJiaDFUbExPRlJXTkRlLXZzemdB"
  },
  {
    id: "caen_musee_des_beaux_arts",
    name: "Caen - Musée des Beaux-Arts",
    country: "France",
    continent: "Europe",
    flag: "🇫🇷",
    region_admin: "Normandie",
    department: "Calvados (14)",
    subdiv: "Caen",
    altitude: 29,
    is_island: false,
    island_name: "",
    transport: "a_pied",
    era_group: "contemporain",
    era_label: "Architecture Muséale Moderne & Peinture Européenne",
    century: "XXe siècle (1971)",
    category: "musee",
    counts: {},
    lat: 49.186291,
    lng: -0.361673,
    image: "https://lh3.googleusercontent.com/pw/AP1GczOEHaZslcQSlmW6Ethv6dvRe0u_EWEzgi_BHScYiWfpd9t02CIQHjrpJbqkjtUKDaG4j-NljCxCx0s0kyQK_Mk6q0QuGqlGyiZ0jiq0DIDB9vw5ldUDUVEUUvK0YyYwMQxv_tAakrVWvDAooeBbhi-KBQ=w613-h919-s-no-gm?authuser=0",
    description: "Implanté au cœur de l'enceinte fortifiée du château ducal, le musée des Beaux-Arts de Caen prend place dans un édifice novateur conçu par l'architecte Jean Atienza et inauguré en 1971. Ce bâtiment moderne et sobre, semi-enterré et habillé de calcaire clair afin de s'intégrer harmonieusement à l'austérité minérale des murailles médiévales environnantes, remplace l'ancien musée détruit lors des bombardements alliés de 1944 au sein du séminaire des Eudistes. L'institution conserve l'un des fonds de peinture les plus riches de France en région, dont le noyau historique provient des saisies révolutionnaires enrichies en 1801 par l'envoi consulaire du décret Chaptal. Les galeries permanentes offrent un parcours chronologique dense à travers l'art européen du XIVe au XXIe siècle, illustré par des chefs-d'œuvre majeurs de la Renaissance italienne et flamande avec Le Pérugin, Cosme Tura, Véronèse ou Brueghel le Jeune. Les collections brillent tout particulièrement par leur ensemble baroque du XVIIe siècle, comptant des toiles maîtresses de Nicolas Poussin, Philippe de Champaigne, Rubens et Le Guerchin, ainsi que par un remarquable panorama de la peinture française des XIXe et XXe siècles. L'expérience muséale s'étend à l'extérieur dans la cour du château avec un vaste parc de sculptures contemporaines exposant des œuvres monumentales signées Rodin, Bourdelle ou Huang Yong Ping.",
    visiter: "Entrer par la vaste façade vitrée ouvrant sur la cour haute pour apprécier la luminosité zénithale des salles d'exposition et la circulation fluide du bâtiment. Rechercher en priorité dans les salles de peinture ancienne le célèbre retable du Mariage de la Vierge du Pérugin et les grandes toiles classiques de Nicolas Poussin. Terminer la découverte en plein air en parcourant le jardin des sculptures contemporaines disséminé sur les pelouses bordant les remparts du château.",
    link: "https://photos.google.com/share/AF1QipP_r-RkUhVBFruOXfc_tByvx5Vje8hgDNED4vVuvCKE6Q2NOmmiqdkWxaQaeFwASQ?key=TklDZmxVZGF4ZTJiaDFUbExPRlJXTkRlLXZzemdB"
  },
  {
    id: "caen_eglise_saint_georges",
    name: "Caen - Église Saint-Georges du Château",
    country: "France",
    continent: "Europe",
    flag: "🇫🇷",
    region_admin: "Normandie",
    department: "Calvados (14)",
    subdiv: "Caen",
    altitude: 29,
    is_island: false,
    island_name: "",
    transport: "a_pied",
    era_group: "medieval",
    era_label: "Chapelle Castrale & Architecture Gothique Normande",
    century: "XIIe siècle",
    category: "religieux",
    counts: {},
    lat: 49.185939,
    lng: -0.362675,
    image: "https://lh3.googleusercontent.com/pw/AP1GczOHHE63OVvmuEXdd4QNW41abqfQSZPL51EWenOdTyUqLUvG8IDgiubnrfRIGnGsM5mTE5Gg2GVJkzdvaRRGlrzHrBUpi6oPs81zyWT-0YogxxEXQtm44nn3DWW2V9-XLT3ajM61OgmvFQ6LO2hHJBx0rA=w1379-h919-s-no-gm?authuser=0",
    description: "Érigée à l'intérieur même de l'enceinte castrale de Guillaume le Conquérant, l'église Saint-Georges assurait sous le duché de Normandie les fonctions de chapelle castrale et de paroisse réservée à la garnison ainsi qu'aux civils résidant dans la haute cour. Mentionnée dès les dernières décennies du XIe siècle, la structure primitive romane a fait l'objet de reconstructions successives et profondes, principalement au cours des XIVe et XVe siècles durant la guerre de Cent Ans. L'édifice actuel, appareillé en pierre calcaire de Caen, illustre la sobriété du gothique normand avec sa nef unique charpentée et son chœur à chevet plat percé de baies lancéolées aux réseaux polylobés délicats. Utilisée comme magasin à poudre puis comme salle de stockage militaire lorsque la forteresse ducale fut reconvertie en caserne au cours des XVIIIe et XIXe siècles, l'église subit d'importantes dégradations intérieures avant d'être sévèrement endommagée par les bombardements de 1944. Restaurée avec soin dans l'après-guerre et désacralisée, elle a été pourvue d'une charpente apparente en berceau évoquant une coque de navire renversée. L'édifice sert désormais d'écrin patrimonial pour l'accueil du musée de Normandie, présentant des expositions temporaires et de grandes maquettes retraçant les métamorphoses topographiques de la forteresse à travers les époques.",
    visiter: "Contempler depuis la pelouse de la cour ducale le profil modeste du chevet plat et les contreforts élancés soutenant les parois calcaires de l'édifice. Pénétrer dans le vaisseau unique pour lever les yeux vers la remarquable charpente en bois formant une voûte lambrissée continue. Détailler les vestiges d'inscriptions et de pierres tombales anciennes enchâssées dans le dallage, ainsi que les panneaux explicatifs et maquettes didactiques retraçant l'évolution médiévale de l'enceinte castrale.",
    link: "https://photos.google.com/share/AF1QipP_r-RkUhVBFruOXfc_tByvx5Vje8hgDNED4vVuvCKE6Q2NOmmiqdkWxaQaeFwASQ?key=TklDZmxVZGF4ZTJiaDFUbExPRlJXTkRlLXZzemdB"
  },
  {
    id: "caen_le_vieux_caen",
    name: "Caen - Le Vieux Caen (Quartier du Vaugueux)",
    country: "France",
    continent: "Europe",
    flag: "🇫🇷",
    region_admin: "Normandie",
    department: "Calvados (14)",
    subdiv: "Caen",
    altitude: 13,
    is_island: false,
    island_name: "",
    transport: "a_pied",
    era_group: "renaissance",
    era_label: "Quartier Historique Préservé & Maisons à Pans de Bois",
    century: "XVIe siècle",
    category: "star",
    counts: {},
    lat: 49.185445,
    lng: -0.359451,
    image: "https://lh3.googleusercontent.com/pw/AP1GczNMtcSFT5nTP6cmD-3SjxmKevACIU3vzgmDO-BiFY0lixyb31rq4Mq2BEkQ5hvFrvkgG_KkIMOC8SiyNy8ePFndOI2IRrxswTO4kwblOzI4lDK1jukMaMHFoKlTbIWUWY0ZwkhUYqtzvqlJWqnqJr7CRg=w1379-h919-s-no-gm?authuser=0",
    description: "Niché au pied des courtines orientales du château ducal, dans le vallon reliant la forteresse à l'abbaye aux Dames, le quartier du Vaugueux constitue l'un des rares îlots médiévaux et Renaissance ayant survécu aux bombardements dévastateurs de la bataille de Normandie en 1944. Ancien faubourg populaire et commerçant établi hors des remparts primitifs dès le Moyen Âge, ce dédale de venelles pavées et étroites est bordé de remarquables demeures construites entre les XVe et XVIIe siècles. Les façades témoignent d'une juxtaposition pittoresque entre la pierre calcaire de Caen, employée pour les rez-de-chaussée et les encadrements de fenêtres à meneaux, et les élévations traditionnelles à pans de bois hourdés de torchis ou de briques. Parmi ses étroites ruelles, la rue du Vaugueux et la rue Porte-au-Berger conservent des façades à encorbellement et de petits passages pavés caractéristiques du tissu urbain normand pré-moderne. Le quartier est également célèbre pour avoir été le lieu d'enfance d'Édith Piaf, qui venait régulièrement y séjourner chez sa grand-mère tenant une maison close rue des Chanoines. Entièrement réhabilité et piétonnisé à partir des années 1970, le secteur forme aujourd'hui le principal cœur gastronomique et animé du centre historique caennais.",
    visiter: "Arpenter la rue pavée du Vaugueux le nez en l'air pour repérer les sablières sculptées, les poteaux corniers ouvragés et les étages en encorbellement des maisons à pans de bois du XVIe siècle. S'engouffrer dans les passages piétons et cours intérieures pavées pour observer les escaliers à vis hors-œuvre taillés dans la pierre de Caen. Profiter de l'ambiance chaleureuse en soirée lorsque les terrasses s'animent face aux façades illuminées au pied du château.",
    link: "https://photos.google.com/share/AF1QipP_r-RkUhVBFruOXfc_tByvx5Vje8hgDNED4vVuvCKE6Q2NOmmiqdkWxaQaeFwASQ?key=TklDZmxVZGF4ZTJiaDFUbExPRlJXTkRlLXZzemdB"
  },
  {
    id: "caen_eglise_saint_pierre",
    name: "Caen - Église Saint-Pierre",
    country: "France",
    continent: "Europe",
    flag: "🇫🇷",
    region_admin: "Normandie",
    department: "Calvados (14)",
    subdiv: "Caen",
    altitude: 6,
    is_island: false,
    island_name: "",
    transport: "a_pied",
    era_group: "renaissance",
    era_label: "Gothique Flamboyant & Chevet Renaissance d'Hector Sohier",
    century: "XIVe siècle",
    category: "religieux",
    counts: {},
    lat: 49.184094,
    lng: -0.360846,
    image: "https://lh3.googleusercontent.com/pw/AP1GczNIsjJrY1c5wMWo5uAJ6qf_8w4dzYSn-LWx_gDrN8goKWX75jW3c-1kZ5uY1zYhYtwo1uIg1oHsqnqavrM2xAw8FpjpCQ1EhDRUYRuCBPSY9KB3BA0fCrbQDTinUHaf-TceVev9AoMWxxu6a7Guxvb6sQ=w1379-h919-s-no-gm?authuser=0",
    description: "Édifiée face aux douves méridionales du château ducal, l'église Saint-Pierre est le principal sanctuaire paroissial du centre historique de Caen et un chef-d'œuvre de la transition stylistique entre le Moyen Âge et la Renaissance. Construit par étapes entre le XIIIe et le XVIe siècle en pierre de Caen, l'édifice est dominé par une prestigieuse tour-clocher du tout début du XIVe siècle, couronnée d'une flèche pyramidale ajourée culminant à plus de soixante-quinze mètres de hauteur, prototype admiré dans toute la Normandie. La nef et les bas-côtés illustrent l'épanouissement du gothique flamboyant avec leurs voûtes à liernes et tiercerons et leurs grandes verrières aux remplages tourmentés. La renommée architecturale de Saint-Pierre repose toutefois sur son chevet d'exception, commandé au maître-maçon normand Hector Sohier entre 1518 et 1545. Ce dernier y déploie un vocabulaire maniériste d'une virtuosité éclatante, ornant les chapelles rayonnantes de voûtes suspendues à pendentifs sculptés vertigineux, de balustrades en candélabres, de pilastres antiquisants et d'angelots d'inspiration italienne. Frappée de plein fouet par un obus de marine britannique dans la nuit du 8 au 9 juin 1944 qui fit s'effondrer sa célèbre flèche sur la nef, l'église a fait l'objet d'une campagne de reconstruction exemplaire achevée en 1957.",
    visiter: "Contempler depuis la place Saint-Pierre l'élancement remarquable du clocher gothique et sa flèche octogonale ajourée réédifiée à l'identique après-guerre. Contourner impérativement l'édifice par la rue de Geôle pour admirer les chapelles rayonnantes du chevet conçues par Hector Sohier, foisonnantes de culots, de niches et de pinacles Renaissance. Franchir le portail sud pour lever les yeux vers les spectaculaires voûtes à clés pendantes du déambulatoire, véritables dentelles de pierre sculptées au XVIe siècle.",
    link: "https://photos.google.com/share/AF1QipP_r-RkUhVBFruOXfc_tByvx5Vje8hgDNED4vVuvCKE6Q2NOmmiqdkWxaQaeFwASQ?key=TklDZmxVZGF4ZTJiaDFUbExPRlJXTkRlLXZzemdB"
  },
  {
    id: "caen_eglise_vieux_saint_sauveur",
    name: "Caen - Église du Vieux Saint-Sauveur",
    country: "France",
    continent: "Europe",
    flag: "🇫🇷",
    region_admin: "Normandie",
    department: "Calvados (14)",
    subdiv: "Caen",
    altitude: 7,
    is_island: false,
    island_name: "",
    transport: "a_pied",
    era_group: "medieval",
    era_label: "Gothique Flamboyant & Église Déconsacrée",
    century: "XVe siècle",
    category: "religieux",
    counts: {},
    lat: 49.183398,
    lng: -0.367815,
    image: "https://lh3.googleusercontent.com/pw/AP1GczMWB4hi6zQnPKSnstqereSZxpOXSy31gJuBs82-Ti2uezyHfXiNr_mxzRFzeLVOEBIkvzuZxzsK3sdxkeRZV6_hnF7ch956M7dX3Y42VtVTJ4SL0cmfzfVsPKaRoEWnWTcQCy03uGkbQADvcpWrz-76EA=w1379-h919-s-no-gm?authuser=0",
    description: "Dressée sur la place Saint-Sauveur au cœur du quartier marchand médiéval de Caen, l'ancienne église paroissiale Saint-Sauveur, dite du « Vieux Saint-Sauveur », offre un précieux témoignage des transformations de l'architecture religieuse normande entre la fin du Moyen Âge et la Renaissance. Initialement fondée sous le règne de Guillaume le Conquérant, l'église conserve dans son clocher latéral des maçonneries du XIIe siècle, mais son allure générale résulte des reconstructions intégrales menées aux XIVe et XVe siècles dans le style gothique flamboyant. Son plan insolite présente une double nef asymétrique, dictée par les contraintes d'alignement parcellaire et l'adjonction progressive de chapelles de confréries. Le chœur à chevet polygonal, réédifié vers 1530-1546 dans l'orbite stylistique des ateliers d'Hector Sohier, mêle arcs brisés et décors sculptés influencés par la Première Renaissance française. Déconsacrée lors de la Révolution au profit de l'église des Cordeliers voisine (qui reprit alors le titre de Saint-Sauveur), la bâtisse échappe de justesse à la démolition pour servir de halle aux blés tout au long du XIXe siècle. Bien que durement éprouvée par les souffles d'explosions et les incendies lors des bombardements alliés de 1944, ses voûtes et ses élévations extérieures en pierre calcaire de Caen ont été minutieusement consolidées, devenant un espace d'expositions culturelles.",
    visiter: "Prendre du recul depuis la vaste place Saint-Sauveur pour apprécier l'asymétrie curieuse de la façade et la silhouette massive de la tour romane coiffée d'une toiture en bâtière. Examiner le chevet polygonal donnant sur la rue Pasteur afin de repérer les détails Renaissance sculptés sur les corniches et les remplages flamboyants des fenêtres hautes. Accéder à l'intérieur lors des manifestations artistiques pour observer le double vaisseau dégagé, les culots sculptés et les vestiges des voûtes en croisée d'ogives.",
    link: "https://photos.google.com/share/AF1QipP_r-RkUhVBFruOXfc_tByvx5Vje8hgDNED4vVuvCKE6Q2NOmmiqdkWxaQaeFwASQ?key=TklDZmxVZGF4ZTJiaDFUbExPRlJXTkRlLXZzemdB"
  },
 {
    id: "caen_vestiges_eglise_saint_gilles",
    name: "Caen - Vestiges de l'Ancienne Église Saint-Gilles",
    country: "France",
    continent: "Europe",
    flag: "🇫🇷",
    region_admin: "Normandie",
    department: "Calvados (14)",
    subdiv: "Caen",
    altitude: 24,
    is_island: false,
    island_name: "",
    transport: "a_pied",
    era_group: "medieval",
    era_label: "Ruines Médiévales & Vestiges des Bombardements",
    century: "XIIe siècle",
    category: "religieux",
    counts: {},
    lat: 49.186571,
    lng: -0.354644,
    image: "https://lh3.googleusercontent.com/pw/AP1GczOdTSSUgq8bTEUGUMleRlHw0QzbL6f_4ePRneIJ-qaHuVvOLQyJxwUBtmcH1gjgToHe4ZxJ3lrPjagPJYHUYwr5kf4Ddq3BHTrwbgpjDfG_0B51JcbVL2d2zDGK5Yy_ijTGkzxJrruoc2h7k2GNSt43sw=w1800-h1201-s-no-gm?authuser=0",
    description: "Dressées au sommet de la colline de la Trinité, à quelques pas de l'enclos monastique de l'abbaye aux Dames, les ruines de l'église Saint-Gilles constituent un témoignage saisissant des ravages de la Seconde Guerre mondiale au cœur de la capitale bas-normande. Fondée initialement au début du XIIe siècle, vers 1110, par la reine Mathilde de Flandre et complétée par son époux Guillaume le Conquérant pour servir d'église paroissiale aux habitants et dépendants du domaine abbatial, la paroisse fut dotée d'un premier édifice roman en pierre de Caen. Reconstruite et agrandie aux XIVe et XVe siècles avec l'adjonction de chapelles latérales et d'éléments de modénature gothique flamboyant, l'église présentait un plan allongé typique de l'architecture urbaine médiévale normande. Le monument traverse les siècles et la Révolution sans dommage majeur, devenant un sujet privilégié pour les peintres paysagistes et les lithographes romantiques du XIXe siècle. Lors de la bataille de Caen à l'été 1944, l'édifice est directement touché et anéanti par les intenses bombardements aériens et les tirs d'artillerie alliés préparant la libération de la ville. Plutôt que de reconstruire le sanctuaire disparu, la municipalité et les Monuments historiques ont fait le choix de stabiliser et de consolider à ciel ouvert les pans de murs, les amorces d'arcatures brisées et les bases des piliers calcinés, offrant un cénotaphe végétalisé en plein air qui dialogue avec le patrimoine mémorial caennais.",
    visiter: "Pénétrer dans le square paysager aménagé autour des vestiges pour détailler le tracé au sol de l'ancienne nef et du chœur délimités par les soubassements en pierre de Caen. Observer les amorces d'arcs brisés et les moulurations gothiques érodées qui subsistent sur les quelques pans de maçonnerie restés debout. Prendre le recul nécessaire depuis le haut de la place Reine-Mathilde pour saisir le contraste visuel saisissant entre la nudité minérale de ces ruines à ciel ouvert et les volumes intacts et imposants de l'abbatiale Sainte-Trinité toute proche.",
    link: "https://photos.google.com/share/AF1QipP_r-RkUhVBFruOXfc_tByvx5Vje8hgDNED4vVuvCKE6Q2NOmmiqdkWxaQaeFwASQ?key=TklDZmxVZGF4ZTJiaDFUbExPRlJXTkRlLXZzemdB"
  },
  {
    id: "caen_abbaye_aux_dames",
    name: "Caen - Abbaye aux Dames",
    country: "France",
    continent: "Europe",
    flag: "🇫🇷",
    region_admin: "Normandie",
    department: "Calvados (14)",
    subdiv: "Caen",
    altitude: 24,
    is_island: false,
    island_name: "",
    transport: "a_pied",
    era_group: "medieval",
    era_label: "Chefd'œuvre de l'Art Roman Normand & Tombeau de la Reine Mathilde",
    century: "XIe siècle (1060)",
    category: "religieux",
    counts: {},
    lat: 49.186476,
    lng: -0.353019,
    image: "https://lh3.googleusercontent.com/pw/AP1GczMXr0Z5eyh8zozv-xGP1-ej_UmH35fUy6tzJ1qFyrf0RGCRRikrAioNuc3FtMaIsUSHHbl03Xpn3F2mRnh7qMnwFQstxvmZRNuiLqta5KIdLWmxPobJs2Xp5tzxt_iacO9FDGfabn0Qr8677xck1QLLTw=w1800-h1201-s-no-gm?authuser=0",
    description: "Fondée vers 1060 par Mathilde de Flandre, épouse de Guillaume le Conquérant, l'abbaye aux Dames (consacrée sous le vocable de la Trinité) est l'un des plus illustres ensembles monastiques de Normandie. Conçue comme l'homologue féminin de l'abbaye aux Hommes, cette fondation bénédictine royale visait à sceller la réconciliation du couple ducal avec la papauté après leur mariage célébré malgré un degré de consanguinité prohibé par le droit canonique. L'église abbatiale, consacrée en 1066 à la veille du départ de la flotte d'invasion vers l'Angleterre, est un sommet de l'architecture romane normande. Construite en pierre calcaire de Caen aux teintes dorées, sa nef imposante présente une élévation à trois niveaux surmontée, dès le début du XIIe siècle, de voûtes d'arêtes sexpartites parmi les premières et les plus hardies de l'Occident chrétien. Le sanctuaire abrite au centre de son chœur la sépulture historique de la reine Mathilde, signalée par une magnifique dalle funéraire de marbre noir du Tournaisis gravée de caractères carolingiens. Au XVIIIe siècle, les bâtiments conventuels furent entièrement reconstruits dans un style classique monumental par l'architecte Guillaume de La Tremblaye, ordonnés autour d'un cloître majestueux et d'un grand escalier d'honneur. Miraculeusement épargnée par les bombardements de 1944 grâce à son statut de refuge hospitalier sous égide de la Croix-Rouge, l'abbaye abrite aujourd'hui le siège du Conseil régional de Normandie.",
    visiter: "Franchir le porche occidental pour contempler la pureté des lignes de la nef romane et la hardiesse technique de ses voûtes d'ogives sexpartites du début du XIIe siècle. S'avancer vers le chœur liturgique afin de se recueillir devant la dalle de marbre noir gravée recouvrant la sépulture de la reine Mathilde. Descendre impérativement dans la crypte romane souterraine, véritable forêt minérale soutenue par seize colonnes monolithes coiffées de chapiteaux historiés remarquablement conservés, avant de déambuler dans les jardins à la française et le parc Michel d'Ornano attenant.",
    link: "https://photos.google.com/share/AF1QipP_r-RkUhVBFruOXfc_tByvx5Vje8hgDNED4vVuvCKE6Q2NOmmiqdkWxaQaeFwASQ?key=TklDZmxVZGF4ZTJiaDFUbExPRlJXTkRlLXZzemdB"
  },
  {
    id: "caen_abbaye_aux_hommes",
    name: "Caen - Abbaye aux Hommes",
    country: "France",
    continent: "Europe",
    flag: "🇫🇷",
    region_admin: "Normandie",
    department: "Calvados (14)",
    subdiv: "Caen",
    altitude: 12,
    is_island: false,
    island_name: "",
    transport: "a_pied",
    era_group: "medieval",
    era_label: "Monument Majeur de l'Art Anglo-Normand & Tombeau de Guillaume le Conquérant",
    century: "XIe siècle (1063)",
    category: "religieux",
    counts: {},
    lat: 49.181852,
    lng: -0.37316,
    image: "https://lh3.googleusercontent.com/pw/AP1GczNq8cpJNL1VGeUl2J0GhsXep2gSyUlt-3AOaadXs_FBx6PsL-MY82KZ3EmBr8UB9jKZuPWFXYq3BlSmjYjFHG9mpMJ-vMAifpjJcOvChjir6NbeUFHRyXtMsa3xALq3HvZPg47D7FmDVn_YG0WW1lqKEQ=w1800-h1201-s-no-gm?authuser=0",
    description: "Fondée en 1063 par Guillaume le Conquérant, duc de Normandie et futur roi d'Angleterre, l'abbaye aux Hommes, dédiée à saint Étienne, forme avec l'abbaye aux Dames le pendant de la pénitence matrimoniale imposée par le pape Léon IX. Chef-d'œuvre fondateur de l'architecture anglo-normande, son abbatiale Saint-Étienne a profondément inspiré les grandes cathédrales d'outre-Manche telles que Durham, Winchester ou Ely. Bâtie en pierre calcaire de Caen, la façade harmonique occidentale offre un modèle d'équilibre et de puissance austère, structurée par de vigoureux contreforts verticaux et sommée de deux imposantes tours romanes couronnées au XIIIe siècle par d'admirables flèches octogonales gothiques culminant à plus de quatre-vingts mètres. L'intérieur de la nef s'élève sur trois niveaux d'une grande rigueur géométrique et accueille le prototype canonique de la voûte d'ogives sexpartite expérimentée vers 1120. Le sanctuaire abrite dans son chœur la dalle tombale de marbre blanc marquant l'emplacement de la sépulture de Guillaume le Conquérant, inhumé ici en 1087 lors d'obsèques mouvementées. Aux XVIIe et XVIIIe siècles, la congrégation de Saint-Maur métamorphosa les bâtiments conventuels attenants en un palais monastique d'esprit classique grandiose, articulé autour d'un vaste cloître toscan et d'un escalier d'honneur en fer forgé. Devenu lycée au XIXe siècle puis hôtel de ville de Caen en 1965, le site a servi d'immense camp de réfugiés sous la protection de la Croix-Rouge lors de l'été 1944, ce qui lui valut d'échapper miraculeusement aux bombardements.",
    visiter: "Admirer depuis l'esplanade Jean-Marie Louvel la façade harmonique et la verticalité des flèches gothiques s'élançant au-dessus des tours romanes. Pénétrer dans l'abbatiale Saint-Étienne pour apprécier la clarté et l'ampleur monumentale de la nef tripartite, puis s'avancer jusqu'au chœur pour observer la dalle funéraire de marbre blanc signalant le tombeau de Guillaume le Conquérant. Prolonger la visite dans les bâtiments conventuels de l'actuel hôtel de ville afin d'admirer les galeries voûtées du cloître classique, le monumental escalier des matines et les lambris de chêne de la salle des mariages.",
    link: "https://photos.google.com/share/AF1QipP_r-RkUhVBFruOXfc_tByvx5Vje8hgDNED4vVuvCKE6Q2NOmmiqdkWxaQaeFwASQ?key=TklDZmxVZGF4ZTJiaDFUbExPRlJXTkRlLXZzemdB"
  },
 {
    id: "ouistreham_musee_mur_atlantique",
    name: "Ouistreham - Musée du Mur de l'Atlantique",
    country: "France",
    continent: "Europe",
    flag: "🇫🇷",
    region_admin: "Normandie",
    department: "Calvados (14)",
    subdiv: "Ouistreham",
    altitude: 6,
    is_island: false,
    island_name: "",
    transport: "a_pied",
    era_group: "contemporain",
    era_label: "Poste de Direction de Tir & Fortification Militaire",
    century: "XXe siècle (1944)",
    category: "musee",
    counts: {},
    lat: 49.287416,
    lng: -0.252389,
    image: "https://lh3.googleusercontent.com/pw/AP1GczM5LVSYmdJQ_NSahpFAYMhVgtQqGFCvkOnzG69gltghHwezm7lumkeXp2wj_z_FU4bYRmR44ZGZvROA0vys8z_4ZqqLAG2mG1RIjMiP5nWMIwNZ5DWfss5YbZw1l1i5Ek0ZLX-83UigmT7wekmALWVYAA=w1800-h1201-s-no-gm?authuser=0",
    description: "Aménagé dans un authentique poste de direction de tir allemand (bunker de type Regelbau H636) achevé début 1944 par l'Organisation Todt, ce musée surnommé « Le Grand Bunker » culmine à dix-sept mètres de hauteur et domine l'embouchure de l'Orne et la baie de Seine. Ce monolithe de béton armé de cinq niveaux, doté de blindages étanches et de murs atteignant par endroits plus de deux mètres d'épaisseur, coordonnait le tir des batteries d'artillerie lourde côtières couvrant le secteur est de la plage de Sword Beach. Lors du Débarquement du 6 juin 1944, l'ouvrage verrouille le front fluvial et résiste pendant trois jours aux tirs de navires alliés et aux assauts terrestres. Il n'est neutralisé que le 9 juin par le lieutenant britannique Bob Orrell du Royal Engineers, qui parvient à dynamiter l'épaisse porte blindée après plusieurs heures d'un siège méthodique. Intégralement réhabilité et transformé en musée de site, le complexe restitue fidèlement l'ambiance confinée et technique de la garnison allemande à travers la reconstitution méticuleuse de ses chambrées, de son infirmerie, de ses salles des machines de filtration d'air, de son central téléphonique et de sa coupole télémétrique sommitale. L'extérieur abrite également la célèbre péniche de débarquement PA 30-4 ayant servi au tournage du film « Il faut sauver le soldat Ryan ».",
    visiter: "Gravir les paliers intérieurs pour explorer chaque niveau fonctionnel du bunker, depuis les installations de survie autonomes au sous-sol jusqu'au central radio parfaitement équipé. Atteindre le sommet pour regarder à travers les optiques du puissant télémètre à coïncidence sous coupole blindée, offrant une vue panoramique directe sur tout le littoral d'Ouistreham et la Manche. Examiner sur l'esplanade extérieure la barge de débarquement de type LCVP ainsi que les canons de DCA et pièces antichars d'époque.",
    link: "https://photos.google.com/share/AF1QipP_r-RkUhVBFruOXfc_tByvx5Vje8hgDNED4vVuvCKE6Q2NOmmiqdkWxaQaeFwASQ?key=TklDZmxVZGF4ZTJiaDFUbExPRlJXTkRlLXZzemdB"
  },
  {
    id: "ouistreham_grande_roue",
    name: "Ouistreham - Grande Roue de Riva-Bella",
    country: "France",
    continent: "Europe",
    flag: "🇫🇷",
    region_admin: "Normandie",
    department: "Calvados (14)",
    subdiv: "Ouistreham",
    altitude: 1,
    is_island: false,
    island_name: "",
    transport: "a_pied",
    era_group: "contemporain",
    era_label: "Panorama Balnéaire & Front de Mer",
    century: "XXIe siècle",
    category: "star",
    counts: {},
    lat: 49.290286,
    lng: -0.257242,
    image: "https://lh3.googleusercontent.com/pw/AP1GczOtlugBOJpMYjbHkce_Hr_E3tjfBnsRL95hCtCFYMZthHK9yu_CbujuUxTIs1ocH0sxnntq6uhAuiCYulhG--w6I_-AcBn1OgTZeCFjYB5ggVgEJDFbeUssodXnVySra_lld8VlMy29MySh9HjNF_fUYA=w1800-h1201-s-no-gm?authuser=0",
    description: "Dressée directement sur l'esplanade du front de mer de Riva-Bella, à la charnière entre le cordon dunaire et la promenade maritime, cette imposante attraction foraine panoramique culmine à près de quarante mètres de hauteur. Conçue avec une structure légère en treillis d'acier blanc et des nacelles ouvertes et vitrées, elle offre un contraste visuel marqué avec l'immense estran sableux découvert à marée basse et la ligne d'horizon rectiligne de la Côte de Nacre. Installée de façon pérenne ou saisonnière selon les périodes au cœur de la station balnéaire fondée au XIXe siècle, la structure permet d'embrasser d'un seul coup d'œil l'ensemble du dispositif topographique du littoral : les jetées du port d'Ouistreham marquant le débouché du canal maritime de Caen, la pointe du Siège et son cordon sableux préservé, ainsi que l'ensemble du secteur de débarquement anglo-français de Sword Beach. À la nuit tombée, son réseau d'éclairage dynamique à LED illumine la promenade piétonne, constituant un repère lumineux visible loin depuis la plage et les quais d'embarquement des ferries transmanche.",
    visiter: "S'approcher depuis la promenade piétonne du front de mer pour saisir en contre-plongée les lignes géométriques blanches de la charpente métallique se découpant sur le ciel marin. Monter à bord des nacelles au moment de la pleine mer ou au coucher du soleil afin de profiter d'un panorama circulaire exceptionnel sur la baie de l'Orne, les villas Belle Époque de Riva-Bella et l'estran de Sword Beach s'étirant vers l'ouest.",
    link: "https://photos.google.com/share/AF1QipP_r-RkUhVBFruOXfc_tByvx5Vje8hgDNED4vVuvCKE6Q2NOmmiqdkWxaQaeFwASQ?key=TklDZmxVZGF4ZTJiaDFUbExPRlJXTkRlLXZzemdB"
  },
  {
    id: "ouistreham_monument_la_flamme",
    name: "Ouistreham - Monument La Flamme",
    country: "France",
    continent: "Europe",
    flag: "🇫🇷",
    region_admin: "Normandie",
    department: "Calvados (14)",
    subdiv: "Ouistreham",
    altitude: 1,
    is_island: false,
    island_name: "",
    transport: "a_pied",
    era_group: "contemporain",
    era_label: "Mémorial aux Commandos Français de Sword Beach",
    century: "XXe siècle (1984)",
    category: "star",
    counts: {},
    lat: 49.290511,
    lng: -0.262337,
    image: "https://lh3.googleusercontent.com/pw/AP1GczOqQWsMDHr1XFUp-ojuG32vo_6VWvuNMRvKnzwMFFmXzhMHLVUmfq2rtWJW__pwJQR1imLSg-7oNjekhCIIow-cslkxiaAFRh0NFMtdJiiVFOLgncyIdQEV5ATPsMOn5qH1GOHmNZSEkiJ5Jy50apuvEQ=w1800-h1199-s-no-gm?authuser=0",
    description: "Érigé au sommet de la dune littorale bordant la plage de Riva-Bella, face à l'immensité de la Manche, le monument commémoratif « La Flamme » a été inauguré le 6 juin 1984 par le président de la République François Mitterrand à l'occasion du 40e anniversaire du Débarquement de Normandie. Œuvre monumentale en métal et béton signée de l'artiste Yvonne Guégan, la sculpture stylise sept langues d'acier inoxydable élancées vers le ciel pour symboliser l'esprit de résistance et l'élan héroïque des soldats de la France libre. L'ouvrage rend un hommage solennel aux cent soixante-dix-sept fusiliers marins du 1er bataillon de fusiliers marins commandos, placé sous le commandement direct du commandant Philippe Kieffer. Intégrés au commando interallié britannique n° 4 au sein de la 1st Special Service Brigade de Lord Lovat, ces hommes furent les seuls Français en uniforme à fouler la terre de Normandie le Jour J. Débarqués à 7 h 31 sous un feu nourri d'armes automatiques et de mortiers, ils eurent pour mission périlleuse d'enlever les redoutables fortifications côtières du point d'appui allemand Wn 10 (le site fortifié du Casino) avant de repiquer vers l'est pour opérer la jonction avec les parachutistes britanniques à Bénouville.",
    visiter: "Gravir les emmarchements de pierre qui mènent au socle surélevé pour contempler la dynamique verticale des lames de métal poli se reflétant dans la lumière côtière. Faire le tour de la base du monument afin de lire les plaques de bronze énumérant les noms des 177 commandos français du bataillon Kieffer, ainsi que les stèles rendant hommage aux disparus des combats du 6 juin. Tourner le regard vers le nord pour appréhender directement l'axe d'assaut des barges de débarquement arrivant sur l'estran découvert à marée basse.",
    link: "https://photos.google.com/share/AF1QipP_r-RkUhVBFruOXfc_tByvx5Vje8hgDNED4vVuvCKE6Q2NOmmiqdkWxaQaeFwASQ?key=TklDZmxVZGF4ZTJiaDFUbExPRlJXTkRlLXZzemdB"
  },
 {
    id: "ouistreham_eglise_saint_samson",
    name: "Ouistreham - Église Saint-Samson",
    country: "France",
    continent: "Europe",
    flag: "🇫🇷",
    region_admin: "Normandie",
    department: "Calvados (14)",
    subdiv: "Ouistreham",
    altitude: 10,
    is_island: false,
    island_name: "",
    transport: "a_pied",
    era_group: "medieval",
    era_label: "Architecture Romane Normande & Église Fortifiée",
    century: "XIIe siècle",
    category: "religieux",
    counts: {},
    lat: 49.276189,
    lng: -0.258053,
    image: "https://lh3.googleusercontent.com/pw/AP1GczNoUPf-BIDUT5rWYfb3z-EApkN9bid5MXnYlQbpvfjOOOOlzvWT8ezmgut-Cg5_X8I7lNGCGRDvGZNAvhHd6MapTOGjDa8QPOY3BrR06sE8qRg7H1kIeFe6MvgB9Esi28ej0LYrGvlCmAVitIsO1WW9hw=w1800-h1201-s-no-gm?authuser=0",
    description: "Édifiée à partir de la seconde moitié du XIIe siècle sur les hauteurs du bourg originel, l'église Saint-Samson constitue un jalon remarquable de l'art roman normand, construite en pierre calcaire de Caen. Dédiée à saint Samson de Dol, l'un des sept saints fondateurs de Bretagne ayant débarqué sur le littoral normand au VIe siècle, elle dépendait sous l'Ancien Régime de la prestigieuse abbaye aux Dames de Caen. L'édifice se distingue par son allure massive et austère, issue de son rôle défensif face aux incursions maritimes venues de la Manche : ses maçonneries épaisses, percées d'ouvertures étroites en meurtrières, servaient de refuge à la population locale, notamment durant les ravages de la guerre de Cent Ans. La façade occidentale est une pièce maîtresse de la sculpture romane régionale, structurée par trois registres d'arcatures aveugles en plein cintre et rythmée par un portail richement sculpté d'archivoltes à bâtons rompus, de frettes crénelées et de modillons figuratifs animaliers. À l'intérieur, la vaste nef romane à trois niveaux d'élévation mène à un chœur et une abside remaniés au XIIIe siècle dans un style gothique primitif élancé, marqué par des voûtes sur croisées d'ogives et des baies lancéolées apportant une vive clarté au sanctuaire. Classé monument historique dès 1840 sur la toute première liste établie par Prosper Mérimée, le monument a également été le témoin direct des combats acharnés menés le 6 juin 1944 par les commandos français du bataillon Kieffer lors de la libération du bourg.",
    visiter: "Prendre du recul sur le parvis pour détailler l'ornementation géométrique du portail ouest, en particulier les chevrons sculptés, les motifs d'entrelacs et la série de modillons anthropomorphes sous la corniche. Faire le tour extérieur par le chevet afin d'observer la transition architecturale entre les puissants contreforts romans de la nef et les baies gothiques plus élancées du chœur. Franchir le portail pour admirer l'élévation intérieure de la nef rythmée par ses grandes arcades retombant sur de lourdes piles circulaires, puis lever les yeux vers la croisée du transept pour examiner la lanterne octogonale coiffant la tour centrale.",
    link: "https://photos.google.com/share/AF1QipP_r-RkUhVBFruOXfc_tByvx5Vje8hgDNED4vVuvCKE6Q2NOmmiqdkWxaQaeFwASQ?key=TklDZmxVZGF4ZTJiaDFUbExPRlJXTkRlLXZzemdB"
  },
 {
    id: "benouville_pegasus_bridge",
    name: "Bénouville - Pegasus Bridge",
    country: "France",
    continent: "Europe",
    flag: "🇫🇷",
    region_admin: "Normandie",
    department: "Calvados (14)",
    subdiv: "Bénouville",
    altitude: 6,
    is_island: false,
    island_name: "",
    transport: "a_pied",
    era_group: "contemporain",
    era_label: "Ouvrage d'Art Métallique & Mémoire du Débarquement",
    century: "XXe siècle (1935)",
    category: "pont",
    counts: {},
    lat: 49.242332,
    lng: -0.273935,
    image: "https://lh3.googleusercontent.com/pw/AP1GczNYr1V1dfwoTR4Kea3DMnCa3VuVOSf8_W6IkWwgGMXx3ol0iPrMoNCu52nqaorKPR4q8BqykZi2tmIPGaXynQ3t8ItNyNIgUJRXubr30MeqKkRQ2Az-kvGPgMZ-3vvOr-DlgvXnYP4OErfyynWvZgWAaA=w1800-h1199-s-no-gm?authuser=0",
    description: "Édifié en 1935 pour franchir le canal de Caen à la mer et relier Bénouville à Ranville, cet ouvrage d'art est un pont basculant métallique à bascule roulante de type Scherzer, reconnaissable à son imposant contrepoids aérien et à ses poutres en treillis riveté. Le site entre dans l'histoire universelle dans la nuit du 5 au 6 juin 1944, lors de l'opération aéroportée Deadstick menée sous le commandement du major John Howard. Déposés à bord de trois planeurs Airspeed Horsa à moins de cinquante mètres des défenses allemandes, les hommes de la 6e division aéroportée britannique de la British Army s'emparent de l'ouvrage en une dizaine de minutes seulement. Cet exploit tactique éclair visait à sécuriser le flanc est de la zone de débarquement d'Ouistreham (Sword Beach) et à empêcher tout contre-assaut de blindés ennemis sur les plages normandes. Rebaptisé officiellement Pegasus Bridge en l'honneur de l'insigne ailé des troupes aéroportées britanniques, le pont d'origine a été déposé et préservé en 1994 afin de permettre le recalibrage du canal maritime. Remplacé in situ par un modèle élargi reprenant scrupuleusement la cinématique et l'architecture industrielle d'origine, le tablier historique repose aujourd'hui dans l'enceinte du musée mémorial voisin.",
    visiter: "Rejoindre à pied le tablier pour examiner le système de bascule Scherzer, ses rails crantés et les contrepoids géants dominant la voie d'eau. Longer les rives du canal jusqu'à l'emplacement des points d'atterrissage des trois planeurs Horsa, matérialisés par des stèles commémoratives sur la rive orientale. Traverser ensuite vers le parc du Mémorial Pegasus afin d'approcher le pont original de 1935 et d'observer de près les traces d'impacts d'obus et de mitraille conservées sur son armature rivetée.",
    link: "https://photos.google.com/share/AF1QipP_r-RkUhVBFruOXfc_tByvx5Vje8hgDNED4vVuvCKE6Q2NOmmiqdkWxaQaeFwASQ?key=TklDZmxVZGF4ZTJiaDFUbExPRlJXTkRlLXZzemdB"
  },
  {
    id: "benouville_cafe_gondree",
    name: "Bénouville - Café Gondrée",
    country: "France",
    continent: "Europe",
    flag: "🇫🇷",
    region_admin: "Normandie",
    department: "Calvados (14)",
    subdiv: "Bénouville",
    altitude: 6,
    is_island: false,
    island_name: "",
    transport: "a_pied",
    era_group: "contemporain",
    era_label: "Bâtiment Historique de la Libération",
    century: "XIXe siècle",
    category: "habitation",
    counts: {},
    lat: 49.24241,
    lng: -0.275021,
    image: "https://lh3.googleusercontent.com/pw/AP1GczOgpuwhqpwlTw3rt4y9OMJkMaDOC2RpX5Iaor0vl3VY8oWl-ngpP9ooF21ka2E_nCpSiDyXrGSC_c4wmUFIg8aVAi7yqFkdiB35Os-8JfpzZHJpxhPlAvTet1Kz2UYKffc4jM9fjHIJa8qdW2foURB3Cw=w1800-h1201-s-no-gm?authuser=0",
    description: "Située sur la rive ouest du canal de Caen à la mer, à quelques dizaines de mètres de la tête de pont de Bénouville, cette bâtisse villageoise construite à la fin du XIXe siècle présente une maçonnerie modeste en briques et enduit sous une toiture d'ardoises. Elle est entrée dans l'histoire de la Seconde Guerre mondiale comme la première maison de France continentale libérée par les forces alliées, quelques minutes après minuit le 6 juin 1944. Tenu à l'époque par Georges et Thérèse Gondrée, qui transmettaient clandestinement des renseignements précieux à la Résistance sur les défenses allemandes locales, l'établissement est immédiatement investi par les hommes du major John Howard dès la prise de Pegasus Bridge. Transformé sur-le-champ en poste de secours médical de fortune, le rez-de-chaussée accueille et soigne les premiers blessés aéroportés de l'opération Overlord, dont le lieutenant Den Brotheridge mortellement touché lors de l'assaut. Toujours entretenu dans un esprit mémoriel vivant et resté propriété de la même famille, le bâtiment demeure un sanctuaire emblématique dédié aux parachutistes britanniques, arborant façades et intérieurs entièrement tapissés d'insignes régimentaires, d'objets militaires et de témoignages de vétérans.",
    visiter: "Observer depuis la berge et la rue les façades d'époque ornées d'enseignes régimentaires britanniques, de plaques commémoratives et de drapeaux alliés. Prendre le recul nécessaire face au canal pour mesurer l'extrême proximité géographique entre le seuil de la bâtisse et l'axe stratégique de Pegasus Bridge. Pénétrer à l'intérieur pour découvrir les murs tapissés de fanions, de photographies d'époque dédicacées par les vétérans et de souvenirs conservés intacts depuis juin 1944.",
    link: "https://photos.google.com/share/AF1QipP_r-RkUhVBFruOXfc_tByvx5Vje8hgDNED4vVuvCKE6Q2NOmmiqdkWxaQaeFwASQ?key=TklDZmxVZGF4ZTJiaDFUbExPRlJXTkRlLXZzemdB"
  },
];
