const SPOTS_2 = [
 {
    id: "ouistreham_eglise_saint_samson",
    name: "Ouistreham - Église Saint-Samson",
    country: "France",
    continent: "Europe",
    flag: "🇫🇷",
    region_admin: "Normandie",
    department: "Calvados (14)",
    subdiv: "Ouistreham",
    altitude: 10,
    is_island: false,
    island_name: "",
    transport: "a_pied",
    era_group: "medieval",
    era_label: "Architecture Romane Normande & Église Fortifiée",
    century: "XIIe siècle",
    category: "religieux",
    counts: {},
    lat: 49.276189,
    lng: -0.258053,
    image: "https://lh3.googleusercontent.com/pw/AP1GczNoUPf-BIDUT5rWYfb3z-EApkN9bid5MXnYlQbpvfjOOOOlzvWT8ezmgut-Cg5_X8I7lNGCGRDvGZNAvhHd6MapTOGjDa8QPOY3BrR06sE8qRg7H1kIeFe6MvgB9Esi28ej0LYrGvlCmAVitIsO1WW9hw=w1800-h1201-s-no-gm?authuser=0",
    description: "Édifiée à partir de la seconde moitié du XIIe siècle sur les hauteurs du bourg originel, l'église Saint-Samson constitue un jalon remarquable de l'art roman normand, construite en pierre calcaire de Caen. Dédiée à saint Samson de Dol, l'un des sept saints fondateurs de Bretagne ayant débarqué sur le littoral normand au VIe siècle, elle dépendait sous l'Ancien Régime de la prestigieuse abbaye aux Dames de Caen. L'édifice se distingue par son allure massive et austère, issue de son rôle défensif face aux incursions maritimes venues de la Manche : ses maçonneries épaisses, percées d'ouvertures étroites en meurtrières, servaient de refuge à la population locale, notamment durant les ravages de la guerre de Cent Ans. La façade occidentale est une pièce maîtresse de la sculpture romane régionale, structurée par trois registres d'arcatures aveugles en plein cintre et rythmée par un portail richement sculpté d'archivoltes à bâtons rompus, de frettes crénelées et de modillons figuratifs animaliers. À l'intérieur, la vaste nef romane à trois niveaux d'élévation mène à un chœur et une abside remaniés au XIIIe siècle dans un style gothique primitif élancé, marqué par des voûtes sur croisées d'ogives et des baies lancéolées apportant une vive clarté au sanctuaire. Classé monument historique dès 1840 sur la toute première liste établie par Prosper Mérimée, le monument a également été le témoin direct des combats acharnés menés le 6 juin 1944 par les commandos français du bataillon Kieffer lors de la libération du bourg.",
    visiter: "Prendre du recul sur le parvis pour détailler l'ornementation géométrique du portail ouest, en particulier les chevrons sculptés, les motifs d'entrelacs et la série de modillons anthropomorphes sous la corniche. Faire le tour extérieur par le chevet afin d'observer la transition architecturale entre les puissants contreforts romans de la nef et les baies gothiques plus élancées du chœur. Franchir le portail pour admirer l'élévation intérieure de la nef rythmée par ses grandes arcades retombant sur de lourdes piles circulaires, puis lever les yeux vers la croisée du transept pour examiner la lanterne octogonale coiffant la tour centrale.",
    link: "https://photos.google.com/share/AF1QipP_r-RkUhVBFruOXfc_tByvx5Vje8hgDNED4vVuvCKE6Q2NOmmiqdkWxaQaeFwASQ?key=TklDZmxVZGF4ZTJiaDFUbExPRlJXTkRlLXZzemdB"
  },
 {
    id: "benouville_pegasus_bridge",
    name: "Bénouville - Pegasus Bridge",
    country: "France",
    continent: "Europe",
    flag: "🇫🇷",
    region_admin: "Normandie",
    department: "Calvados (14)",
    subdiv: "Bénouville",
    altitude: 6,
    is_island: false,
    island_name: "",
    transport: "a_pied",
    era_group: "contemporain",
    era_label: "Ouvrage d'Art Métallique & Mémoire du Débarquement",
    century: "XXe siècle (1935)",
    category: "pont",
    counts: {},
    lat: 49.242332,
    lng: -0.273935,
    image: "https://lh3.googleusercontent.com/pw/AP1GczNYr1V1dfwoTR4Kea3DMnCa3VuVOSf8_W6IkWwgGMXx3ol0iPrMoNCu52nqaorKPR4q8BqykZi2tmIPGaXynQ3t8ItNyNIgUJRXubr30MeqKkRQ2Az-kvGPgMZ-3vvOr-DlgvXnYP4OErfyynWvZgWAaA=w1800-h1199-s-no-gm?authuser=0",
    description: "Édifié en 1935 pour franchir le canal de Caen à la mer et relier Bénouville à Ranville, cet ouvrage d'art est un pont basculant métallique à bascule roulante de type Scherzer, reconnaissable à son imposant contrepoids aérien et à ses poutres en treillis riveté. Le site entre dans l'histoire universelle dans la nuit du 5 au 6 juin 1944, lors de l'opération aéroportée Deadstick menée sous le commandement du major John Howard. Déposés à bord de trois planeurs Airspeed Horsa à moins de cinquante mètres des défenses allemandes, les hommes de la 6e division aéroportée britannique de la British Army s'emparent de l'ouvrage en une dizaine de minutes seulement. Cet exploit tactique éclair visait à sécuriser le flanc est de la zone de débarquement d'Ouistreham (Sword Beach) et à empêcher tout contre-assaut de blindés ennemis sur les plages normandes. Rebaptisé officiellement Pegasus Bridge en l'honneur de l'insigne ailé des troupes aéroportées britanniques, le pont d'origine a été déposé et préservé en 1994 afin de permettre le recalibrage du canal maritime. Remplacé in situ par un modèle élargi reprenant scrupuleusement la cinématique et l'architecture industrielle d'origine, le tablier historique repose aujourd'hui dans l'enceinte du musée mémorial voisin.",
    visiter: "Rejoindre à pied le tablier pour examiner le système de bascule Scherzer, ses rails crantés et les contrepoids géants dominant la voie d'eau. Longer les rives du canal jusqu'à l'emplacement des points d'atterrissage des trois planeurs Horsa, matérialisés par des stèles commémoratives sur la rive orientale. Traverser ensuite vers le parc du Mémorial Pegasus afin d'approcher le pont original de 1935 et d'observer de près les traces d'impacts d'obus et de mitraille conservées sur son armature rivetée.",
    link: "https://photos.google.com/share/AF1QipP_r-RkUhVBFruOXfc_tByvx5Vje8hgDNED4vVuvCKE6Q2NOmmiqdkWxaQaeFwASQ?key=TklDZmxVZGF4ZTJiaDFUbExPRlJXTkRlLXZzemdB"
  },
  {
    id: "benouville_cafe_gondree",
    name: "Bénouville - Café Gondrée",
    country: "France",
    continent: "Europe",
    flag: "🇫🇷",
    region_admin: "Normandie",
    department: "Calvados (14)",
    subdiv: "Bénouville",
    altitude: 6,
    is_island: false,
    island_name: "",
    transport: "a_pied",
    era_group: "contemporain",
    era_label: "Bâtiment Historique de la Libération",
    century: "XIXe siècle",
    category: "habitation",
    counts: {},
    lat: 49.24241,
    lng: -0.275021,
    image: "https://lh3.googleusercontent.com/pw/AP1GczOgpuwhqpwlTw3rt4y9OMJkMaDOC2RpX5Iaor0vl3VY8oWl-ngpP9ooF21ka2E_nCpSiDyXrGSC_c4wmUFIg8aVAi7yqFkdiB35Os-8JfpzZHJpxhPlAvTet1Kz2UYKffc4jM9fjHIJa8qdW2foURB3Cw=w1800-h1201-s-no-gm?authuser=0",
    description: "Située sur la rive ouest du canal de Caen à la mer, à quelques dizaines de mètres de la tête de pont de Bénouville, cette bâtisse villageoise construite à la fin du XIXe siècle présente une maçonnerie modeste en briques et enduit sous une toiture d'ardoises. Elle est entrée dans l'histoire de la Seconde Guerre mondiale comme la première maison de France continentale libérée par les forces alliées, quelques minutes après minuit le 6 juin 1944. Tenu à l'époque par Georges et Thérèse Gondrée, qui transmettaient clandestinement des renseignements précieux à la Résistance sur les défenses allemandes locales, l'établissement est immédiatement investi par les hommes du major John Howard dès la prise de Pegasus Bridge. Transformé sur-le-champ en poste de secours médical de fortune, le rez-de-chaussée accueille et soigne les premiers blessés aéroportés de l'opération Overlord, dont le lieutenant Den Brotheridge mortellement touché lors de l'assaut. Toujours entretenu dans un esprit mémoriel vivant et resté propriété de la même famille, le bâtiment demeure un sanctuaire emblématique dédié aux parachutistes britanniques, arborant façades et intérieurs entièrement tapissés d'insignes régimentaires, d'objets militaires et de témoignages de vétérans.",
    visiter: "Observer depuis la berge et la rue les façades d'époque ornées d'enseignes régimentaires britanniques, de plaques commémoratives et de drapeaux alliés. Prendre le recul nécessaire face au canal pour mesurer l'extrême proximité géographique entre le seuil de la bâtisse et l'axe stratégique de Pegasus Bridge. Pénétrer à l'intérieur pour découvrir les murs tapissés de fanions, de photographies d'époque dédicacées par les vétérans et de souvenirs conservés intacts depuis juin 1944.",
    link: "https://photos.google.com/share/AF1QipP_r-RkUhVBFruOXfc_tByvx5Vje8hgDNED4vVuvCKE6Q2NOmmiqdkWxaQaeFwASQ?key=TklDZmxVZGF4ZTJiaDFUbExPRlJXTkRlLXZzemdB"
  },
];
